In [1]:
import pandas as pd
import time
import numpy as np
import os
# Load datasets from ml-latest-small folder
df_movies = pd.read_csv(os.path.join('ml-latest-small', 'movies.csv'))
df_ratings = pd.read_csv(os.path.join('ml-latest-small', 'ratings.csv'))
df_tags = pd.read_csv(os.path.join('ml-latest-small', 'tags.csv'))  


tags_grouped = df_tags.groupby('movieId')['tag'].apply(lambda x: ','.join(x)).reset_index()


# Merge tags with movies
movies_tag = pd.merge(df_movies, tags_grouped, on='movieId', how='left')
movies_tag['tag'] = movies_tag['tag'].fillna('')

 

movies_tag['combined_features'] = movies_tag['genres'] + ' ' + movies_tag['tag']

 

# Merge rate with movies_tag
movies_tag_rate = pd.merge(df_ratings,movies_tag,  on='movieId', how='left')

 

#calculate age in year and add a new column weighted_rating
movies_tag_rate['age_year']= round((round(time.time() )- movies_tag_rate['timestamp'])/(24*3600*365))
movies_tag_rate['weighted_rating'] = movies_tag_rate['rating'] *1/ movies_tag_rate['age_year']

 

 

 

# Calculate the mean of weighted_rating for each movie and sort it

movies_tag_rate.groupby("movieId").agg({

        "weighted_rating": "mean",

        "title": "first"

    }).sort_values(by="weighted_rating", ascending=False).reset_index()

      movieId  weighted_rating                                         title
0      172875         0.714286                      A Detective Story (2003)
1      187717         0.714286              Won't You Be My Neighbor? (2018)
2       33649         0.714286                            Saving Face (2004)
3      179135         0.714286                         Blue Planet II (2017)
4      136556         0.714286  Kung Fu Panda: Secrets of the Masters (2011)
...       ...              ...                                           ...
9719     5105         0.023810                         Don't Look Now (1973)
9720     7742         0.023810                                 Baxter (1989)
9721     6967         0.023810                          Dead of Night (1945)
9722     5700         0.022727                            The Pumaman (1980)
9723     5771         0.021739                    My Bloody Valentine (1981)

[9724 rows x 3 columns]

In [5]:
import pandas as pd
import time
import numpy as np
import os
# Load datasets from ml-latest-small folder
df_movies = pd.read_csv(os.path.join('ml-latest-small', 'movies.csv'))
df_ratings = pd.read_csv(os.path.join('ml-latest-small', 'ratings.csv'))
df_tags = pd.read_csv(os.path.join('ml-latest-small', 'tags.csv'))  


tags_grouped = df_tags.groupby('movieId')['tag'].apply(lambda x: ','.join(x)).reset_index()


# Merge tags with movies
movies_tag = pd.merge(df_movies, tags_grouped, on='movieId', how='left')
movies_tag['tag'] = movies_tag['tag'].fillna('')

 

movies_tag['combined_features'] = movies_tag['genres'] + ' ' + movies_tag['tag']

 

# Merge rate with movies_tag
movies_tag_rate = pd.merge(df_ratings,movies_tag,  on='movieId', how='left')

 
# Calculate the count of rating for each movie 

weighted_movie_rate=movies_tag_rate.groupby(["movieId","title"]).agg({

        "rating": ["count" , "mean"]

    }).reset_index()
#.sort_values(by="rating", ascending=False).reset_index()
m=20;




def imbd_rating(movie_rate:pd.DataFrame, m=20)->pd.DataFrame:
    #score=v/(v+m).R +  m/(v+m).C
    #R: average
    #v: count
    R=movie_rate.groupby('movieId')['rating'].mean()
    v=movie_rate.groupby('movieId')['rating'].count()
    C=movie_rate['rating'].mean() 
    term1 = (v /(v +m))*R
    term2 = m/(v +m)*C
    return term1 + term2    

movies_tag_rate['weighted_rating']=imbd_rating(movies_tag_rate,m=m)
movies_tag_rate.columns

movies_tag_rate.sort_values(by='weighted_rating', ascending=False,inplace=True)
#Display top 10 moives with genra "Action"
movies_tag_rate[movies_tag_rate['genres'].str.contains('Action')].head(10)

,userId,movieId,rating,timestamp,title,genres,tag,combined_features,weighted_rating
318,4,260,5.0,945079259,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,"classic,space action,action,sci-fi,EPIC,great ...","Action|Adventure|Sci-Fi classic,space action,a...",4.373980
2959,19,3745,4.0,965702776,Titan A.E. (2000),Action|Adventure|Animation|Children|Sci-Fi,,Action|Adventure|Animation|Children|Sci-Fi,4.208114
296,3,7991,5.0,1306463684,Death Race 2000 (1975),Action|Sci-Fi,,Action|Sci-Fi,4.154529
1196,10,63113,3.5,1455302183,Quantum of Solace (2008),Action|Adventure|Thriller,,Action|Adventure|Thriller,4.153814
48516,313,3697,5.0,1030474952,Predator 2 (1990),Action|Sci-Fi|Thriller,,Action|Sci-Fi|Thriller,4.134103
2329,19,330,3.0,965705097,Tales from the Hood (1995),Action|Crime|Horror,,Action|Crime|Horror,4.121014
2028,18,7373,3.5,1455049881,Hellboy (2004),Action|Adventure|Fantasy|Horror,,Action|Adventure|Fantasy|Horror,4.084284
7361,50,122918,1.0,1514239279,Guardians of the Galaxy 2 (2017),Action|Adventure|Sci-Fi,fun,Action|Adventure|Sci-Fi fun,4.073054
1276,11,377,3.0,902154431,Speed (1994),Action|Romance|Thriller,bus,Action|Romance|Thriller bus,4.071833
4226,28,442,1.0,1234516283,Demolition Man (1993),Action|Adventure|Sci-Fi,,Action|Adventure|Sci-Fi,4.053247

In [ ]:
term1 = (weighted_movie_rate[('rating', 'count')] /(weighted_movie_rate[('rating', 'count')]+m))*weighted_movie_rate[('rating', 'mean')]
term2=m/(weighted_movie_rate[('rating', 'count')]+m)*C
weighted_movie_rate['weighted_rating'] = term1+term2
weighted_movie_rate.sort_values(by="weighted_rating", ascending=False).reset_index()