# <center> Module 6: Recommender Systems</center>
## <center> Collaborative Filtering: Model Based Recommenders <br> MovieLens Movies Database </center>
<center>by: Nicole Woodland, P. Eng. for RoboGarden Inc. </center>

---

#### Ask the Right Question:

In this example, we have a database of Users and the ratings they have given to various movies. <br> Can we use this data to make movies recommendations to the user?

### <font color='blue'> Download the Dataset </font>
Download the Dataset from the following link: <br>
https://www.kaggle.com/rounakbanik/the-movies-dataset?select=movies_metadata.csv

In [3]:
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

There are a few steps to install SciKit-Surprise:
1. Install VS Code from: https://code.visualstudio.com/docs/setup/windows
2. Install the dependencies for C++ builder from: https://visualstudio.microsoft.com/visual-cpp-build-tools/
3. Run the pip command line below by uncommenting the pip install command
4. May need to reversion Python to 3.10 and numpy to 1.9?

In [5]:
#pip install scikit-surprise

<font color = "blue"> Read the dataset into the Pandas Data Frame!

In [11]:
import pandas as pd
#Load the small dataset
ratings = pd.read_csv("../ratings.csv")
#ratings = pd.read_csv("ratings_small.csv")

In [15]:
ratings.head(30)

    userId  movieId  rating   timestamp
0        1      110     1.0  1425941529
1        1      147     4.5  1425942435
2        1      858     5.0  1425941523
3        1     1221     5.0  1425941546
4        1     1246     5.0  1425941556
5        1     1968     4.0  1425942148
6        1     2762     4.5  1425941300
7        1     2918     5.0  1425941593
8        1     2959     4.0  1425941601
9        1     4226     4.0  1425942228
10       1     4878     5.0  1425941434
11       1     5577     5.0  1425941397
12       1    33794     4.0  1425942005
13       1    54503     3.5  1425941313
14       1    58559     4.0  1425942007
15       1    59315     5.0  1425941502
16       1    68358     5.0  1425941464
17       1    69844     5.0  1425942139
18       1    73017     5.0  1425942699
19       1    81834     5.0  1425942133
20       1    91500     2.5  1425942647
21       1    91542     5.0  1425942618
22       1    92439     5.0  1425941424
23       1    96821     5.0  1425941382
24       1    98809     0.5  1425942640
25       1    99114     4.0  1425941667
26       1   112552     5.0  1425941336
27       2        5     3.0   867039249
28       2       25     3.0   867039168
29       2       32     2.0   867039166

In [5]:
mov_ids = ratings.movieId.unique()
print(mov_ids)
print(len(mov_ids))

[   110    147    858 ... 165649 171051 171221]
45115

In [10]:
ratings.tail(10)

          userId  movieId  rating   timestamp
26024279  270896    54286     4.5  1257031701
26024280  270896    54503     4.0  1257033886
26024281  270896    55820     5.0  1257031660
26024282  270896    56174     3.5  1257034085
26024283  270896    56367     4.5  1257031529
26024284  270896    58559     5.0  1257031564
26024285  270896    60069     5.0  1257032032
26024286  270896    63082     4.5  1257031764
26024287  270896    64957     4.5  1257033990
26024288  270896    71878     2.0  1257031858

## Create a Model-Based Collaborative Filtering Recommender

In [17]:
ratings = ratings.drop('timestamp', axis = 1)

In [19]:
ratings

          userId  movieId  rating
0              1      110     1.0
1              1      147     4.5
2              1      858     5.0
3              1     1221     5.0
4              1     1246     5.0
...          ...      ...     ...
26024284  270896    58559     5.0
26024285  270896    60069     5.0
26024286  270896    63082     4.5
26024287  270896    64957     4.5
26024288  270896    71878     2.0

[26024289 rows x 3 columns]

In [14]:
ratings.iloc[:,0:1].values

array([[     1],
       [     1],
       [     1],
       ...,
       [270896],
       [270896],
       [270896]], dtype=int64)

### Import Surprise, and define data and and training and test sets

In [21]:
from surprise import Dataset, Reader
reader = Reader()

#Columns in df must be in the order profile_ID, Item_ID, Item_rating
data = Dataset.load_from_df(ratings, reader)

In [22]:
data

In [25]:
from surprise.model_selection import train_test_split
trainset, testset = train_test_split(data, test_size=0.25)

In [29]:
# Train the model - aka, guess the ratings users would make by determining the best case latent matrices for users and items
from surprise import SVD, accuracy
svd = SVD()
svd.fit(trainset)

In [30]:
# Check model performance:
trainset_predictions = [
    (trainset.to_raw_uid(uid), trainset.to_raw_iid(iid), rating)
    for uid, iid, rating in trainset.all_ratings()]
predictions = svd.test(trainset_predictions)
print("Training score:",accuracy.mse(predictions))

## THis part is typical process:
predictions = svd.test(testset)
print("Testing Score:",accuracy.mse(predictions))

MSE: 0.4585
Training score: 0.45845845111808425
MSE: 0.6398
Testing Score: 0.6398397531015764

This corresponds to 0.8 out of 5 units of error across the board. In the general sense, this is 'good enough' to give an idea if a user will have a positive or negative reaction to an item. Especially in a dataset where there is a high degree of subjectiveness in the data collection. The training score and tresting score are also similar, so the model should be reasonably fit.

In [20]:
predictions

[Prediction(uid=57847, iid=1674, r_ui=4.5, est=3.321250785979138, details={'was_impossible': False}),
 Prediction(uid=14793, iid=4878, r_ui=4.0, est=3.9183541887591, details={'was_impossible': False}),
 Prediction(uid=4480, iid=253, r_ui=4.5, est=3.7508305076744533, details={'was_impossible': False}),
 Prediction(uid=90203, iid=2496, r_ui=2.5, est=2.017369980049548, details={'was_impossible': False}),
 Prediction(uid=102651, iid=103141, r_ui=2.0, est=2.649006729539745, details={'was_impossible': False}),
 Prediction(uid=188851, iid=58975, r_ui=3.5, est=3.203356454613935, details={'was_impossible': False}),
 Prediction(uid=169074, iid=131160, r_ui=4.0, est=3.6033542413549218, details={'was_impossible': False}),
 Prediction(uid=260339, iid=73017, r_ui=4.5, est=4.11308817685027, details={'was_impossible': False}),
 Prediction(uid=220375, iid=508, r_ui=4.0, est=3.9344446644789164, details={'was_impossible': False}),
 Prediction(uid=24905, iid=2502, r_ui=4.0, est=3.6354969736075984, details={'was_impossible': False}),
 Prediction(uid=222446, iid=5445, r_ui=4.0, est=3.306084853295908, details={'was_impossible': False}),
 Prediction(uid=219171, iid=34437, r_ui=3.5, est=3.659784978033132, details={'was_impossible': False}),
 Prediction(uid=144983, iid=1097, r_ui=5.0, est=4.644341346345779, details={'was_impossible': False}),
 Prediction(uid=153839, iid=1208, r_ui=4.5, est=3.836187638051275, details={'was_impossible': False}),
 Prediction(uid=235099, iid=91529, r_ui=3.5, est=3.4523834822955877, details={'was_impossible': False}),
 Prediction(uid=60213, iid=151, r_ui=5.0, est=3.4974829044688103, details={'was_impossible': False}),
 Prediction(uid=63058, iid=54276, r_ui=1.5, est=2.844942963914484, details={'was_impossible': False}),
 Prediction(uid=18830, iid=165, r_ui=4.0, est=4.37530271435535, details={'was_impossible': False}),
 Prediction(uid=237731, iid=2424, r_ui=4.0, est=4.150808764425161, details={'was_impossible': False}),
 Prediction(uid=67307, iid=405, r_ui=4.0, est=3.1354824493070934, details={'was_impossible': False}),
 Prediction(uid=221823, iid=8665, r_ui=4.0, est=4.250907113295377, details={'was_impossible': False}),
 Prediction(uid=231770, iid=6503, r_ui=3.5, est=3.3310707105125936, details={'was_impossible': False}),
 Prediction(uid=157644, iid=165, r_ui=5.0, est=4.813129907824971, details={'was_impossible': False}),
 Prediction(uid=208672, iid=8370, r_ui=5.0, est=3.9802641976114694, details={'was_impossible': False}),
 Prediction(uid=57929, iid=2710, r_ui=3.0, est=3.0963853697080927, details={'was_impossible': False}),
 Prediction(uid=102207, iid=4033, r_ui=3.5, est=3.7733132335770656, details={'was_impossible': False}),
 Prediction(uid=149653, iid=1304, r_ui=3.0, est=3.81247270244231, details={'was_impossible': False}),
 Prediction(uid=43976, iid=3274, r_ui=3.0, est=2.5837971309401517, details={'was_impossible': False}),
 Prediction(uid=268682, iid=4979, r_ui=3.5, est=2.8713136451169055, details={'was_impossible': False}),
 Prediction(uid=267236, iid=1199, r_ui=4.0, est=3.7320170029412387, details={'was_impossible': False}),
 Prediction(uid=130752, iid=296, r_ui=4.5, est=3.9694908230596124, details={'was_impossible': False}),
 Prediction(uid=27383, iid=778, r_ui=3.5, est=3.9088314989336035, details={'was_impossible': False}),
 Prediction(uid=9983, iid=69644, r_ui=5.0, est=4.13468945828547, details={'was_impossible': False}),
 Prediction(uid=249944, iid=72165, r_ui=4.0, est=3.466868313809056, details={'was_impossible': False}),
 Prediction(uid=93474, iid=3070, r_ui=4.0, est=4.037376650438674, details={'was_impossible': False}),
 Prediction(uid=238675, iid=79132, r_ui=4.0, est=4.740544876707984, details={'was_impossible': False}),
 Prediction(uid=87000, iid=1357, r_ui=4.0, est=3.809154802627645, details={'was_impossible': False}),
 Prediction(uid=15038, iid=3535, r_ui=1.0, est=1.9902732512967776, details={'was_impossible': False}),
 Prediction(uid=177251, iid=3717, r_ui=2.0, est=2.3242004992549696, details={'was_impossible': False}),
 Prediction(uid=189383, iid=316, r_ui=3.0, est=2.8479850274890692, details={'was_impossible': False}),
 Prediction(uid=193481, iid=80590, r_ui=3.5, est=3.110167608862485, details={'was_impossible': False}),
 Prediction(uid=51075, iid=48780, r_ui=4.0, est=4.4188157151999645, details={'was_impossible': False}),
 Prediction(uid=66285, iid=743, r_ui=2.0, est=2.2082160312183183, details={'was_impossible': False}),
 Prediction(uid=189241, iid=73804, r_ui=3.0, est=2.744426295958945, details={'was_impossible': False}),
 Prediction(uid=55447, iid=59501, r_ui=1.0, est=1.5112745277622968, details={'was_impossible': False}),
 Prediction(uid=130476, iid=6378, r_ui=3.5, est=3.782506458893955, details={'was_impossible': False}),
 Prediction(uid=230165, iid=2571, r_ui=5.0, est=3.2230269203342723, details={'was_impossible': False}),
 Prediction(uid=10681, iid=272, r_ui=3.0, est=3.35656764653234, details={'was_impossible': False}),
 Prediction(uid=105064, iid=1785, r_ui=4.0, est=4.063206304906019, details={'was_impossible': False}),
 Prediction(uid=104057, iid=1729, r_ui=4.0, est=3.241990115639478, details={'was_impossible': False}),
 Prediction(uid=258823, iid=8874, r_ui=3.5, est=3.506921662757088, details={'was_impossible': False}),
 Prediction(uid=198088, iid=110, r_ui=5.0, est=4.7572645344689946, details={'was_impossible': False}),
 Prediction(uid=229460, iid=4226, r_ui=3.5, est=4.135283394328702, details={'was_impossible': False}),
 Prediction(uid=176960, iid=2968, r_ui=5.0, est=4.685314410818334, details={'was_impossible': False}),
 Prediction(uid=250047, iid=4040, r_ui=3.5, est=3.3422187039406817, details={'was_impossible': False}),
 Prediction(uid=143998, iid=307, r_ui=3.0, est=4.501518190146614, details={'was_impossible': False}),
 Prediction(uid=144727, iid=1172, r_ui=3.5, est=3.888706548852329, details={'was_impossible': False}),
 Prediction(uid=244879, iid=589, r_ui=3.0, est=3.6907338406945183, details={'was_impossible': False}),
 Prediction(uid=187224, iid=5025, r_ui=4.0, est=3.87647024848327, details={'was_impossible': False}),
 Prediction(uid=38014, iid=64614, r_ui=4.0, est=3.747747334171322, details={'was_impossible': False}),
 Prediction(uid=33576, iid=2706, r_ui=2.0, est=2.76674135419658, details={'was_impossible': False}),
 Prediction(uid=169751, iid=784, r_ui=3.0, est=3.2827702501850466, details={'was_impossible': False}),
 Prediction(uid=214713, iid=590, r_ui=3.0, est=3.328039382031915, details={'was_impossible': False}),
 Prediction(uid=210033, iid=673, r_ui=2.0, est=2.1469162978333634, details={'was_impossible': False}),
 Prediction(uid=147512, iid=163645, r_ui=2.5, est=3.356847011023878, details={'was_impossible': False}),
 Prediction(uid=51320, iid=3831, r_ui=4.0, est=3.665376850967658, details={'was_impossible': False}),
 Prediction(uid=39585, iid=5667, r_ui=4.0, est=3.4057970439509404, details={'was_impossible': False}),
 Prediction(uid=17454, iid=32587, r_ui=3.0, est=3.1651980405090945, details={'was_impossible': False}),
 Prediction(uid=63380, iid=1186, r_ui=4.0, est=4.05144556307301, details={'was_impossible': False}),
 Prediction(uid=102237, iid=68954, r_ui=5.0, est=4.358428699717189, details={'was_impossible': False}),
 Prediction(uid=132462, iid=2336, r_ui=5.0, est=3.7623532253932988, details={'was_impossible': False}),
 Prediction(uid=237973, iid=216, r_ui=4.0, est=4.445547405114354, details={'was_impossible': False}),
 Prediction(uid=171357, iid=589, r_ui=4.0, est=4.349394310978097, details={'was_impossible': False}),
 Prediction(uid=155025, iid=1244, r_ui=3.0, est=3.589742583887658, details={'was_impossible': False}),
 Prediction(uid=54784, iid=1733, r_ui=4.0, est=3.625479164088993, details={'was_impossible': False}),
 Prediction(uid=70558, iid=2871, r_ui=4.0, est=4.248839576307258, details={'was_impossible': False}),
 Prediction(uid=225186, iid=21, r_ui=2.0, est=3.546836126934032, details={'was_impossible': False}),
 Prediction(uid=101087, iid=4023, r_ui=4.0, est=3.7090574968657464, details={'was_impossible': False}),
 Prediction(uid=267018, iid=50, r_ui=5.0, est=4.213369157676956, details={'was_impossible': False}),
 Prediction(uid=224621, iid=2490, r_ui=1.0, est=2.299716744248172, details={'was_impossible': False}),
 Prediction(uid=145130, iid=711, r_ui=5.0, est=4.279463365112645, details={'was_impossible': False}),
 Prediction(uid=97132, iid=2050, r_ui=1.5, est=2.9539174243905917, details={'was_impossible': False}),
 Prediction(uid=260122, iid=172, r_ui=3.0, est=3.3879151944203953, details={'was_impossible': False}),
 Prediction(uid=12304, iid=1270, r_ui=4.5, est=3.909663541463039, details={'was_impossible': False}),
 Prediction(uid=56391, iid=1394, r_ui=5.0, est=4.145498639360182, details={'was_impossible': False}),
 Prediction(uid=153037, iid=648, r_ui=5.0, est=4.202502919855231, details={'was_impossible': False}),
 Prediction(uid=175663, iid=15, r_ui=4.0, est=2.787620161965255, details={'was_impossible': False}),
 Prediction(uid=84861, iid=1921, r_ui=4.0, est=4.65619039055579, details={'was_impossible': False}),
 Prediction(uid=168335, iid=48394, r_ui=4.5, est=3.563816814881398, details={'was_impossible': False}),
 Prediction(uid=187534, iid=69, r_ui=3.0, est=3.1710522662179748, details={'was_impossible': False}),
 Prediction(uid=20024, iid=42009, r_ui=0.5, est=1.7944486014755672, details={'was_impossible': False}),
 Prediction(uid=187033, iid=93, r_ui=4.0, est=3.192697973588983, details={'was_impossible': False}),
 Prediction(uid=74850, iid=3147, r_ui=3.5, est=3.908413841855009, details={'was_impossible': False}),
 Prediction(uid=205918, iid=7018, r_ui=4.0, est=3.724784320494179, details={'was_impossible': False}),
 Prediction(uid=73842, iid=3535, r_ui=4.5, est=3.9286828342639337, details={'was_impossible': False}),
 Prediction(uid=236491, iid=1265, r_ui=4.0, est=3.7141694518617596, details={'was_impossible': False}),
 Prediction(uid=122600, iid=55290, r_ui=3.5, est=3.376742311579505, details={'was_impossible': False}),
 Prediction(uid=11962, iid=2294, r_ui=4.0, est=3.498112944490675, details={'was_impossible': False}),
 Prediction(uid=37130, iid=5010, r_ui=4.0, est=3.7878653656713674, details={'was_impossible': False}),
 Prediction(uid=107972, iid=3949, r_ui=4.5, est=4.079692613447888, details={'was_impossible': False}),
 Prediction(uid=72776, iid=1036, r_ui=5.0, est=4.327405260605664, details={'was_impossible': False}),
 Prediction(uid=230881, iid=4974, r_ui=4.0, est=3.927171223822122, details={'was_impossible': False}),
 Prediction(uid=179259, iid=2987, r_ui=3.0, est=2.944542761259994, details={'was_impossible': False}),
 Prediction(uid=185835, iid=708, r_ui=5.0, est=4.512257489761121, details={'was_impossible': False}),
 Prediction(uid=41611, iid=260, r_ui=5.0, est=3.989043786722204, details={'was_impossible': False}),
 Prediction(uid=125764, iid=62155, r_ui=4.0, est=3.5019071270884887, details={'was_impossible': False}),
 Prediction(uid=118874, iid=1250, r_ui=5.0, est=4.6730856066427, details={'was_impossible': False}),
 Prediction(uid=88894, iid=106782, r_ui=4.0, est=3.756306287826965, details={'was_impossible': False}),
 Prediction(uid=88069, iid=25, r_ui=5.0, est=3.8517441058386983, details={'was_impossible': False}),
 Prediction(uid=98334, iid=1036, r_ui=4.5, est=4.035548578527408, details={'was_impossible': False}),
 Prediction(uid=49327, iid=4143, r_ui=1.0, est=1.2983516306675602, details={'was_impossible': False}),
 Prediction(uid=245947, iid=55247, r_ui=4.0, est=3.8015817828796292, details={'was_impossible': False}),
 Prediction(uid=257901, iid=141, r_ui=4.0, est=3.556861241882821, details={'was_impossible': False}),
 Prediction(uid=45007, iid=1221, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=145806, iid=8783, r_ui=2.5, est=3.115076453022129, details={'was_impossible': False}),
 Prediction(uid=201676, iid=648, r_ui=4.0, est=3.7469698183751348, details={'was_impossible': False}),
 Prediction(uid=205547, iid=2485, r_ui=2.5, est=2.1984568043957506, details={'was_impossible': False}),
 Prediction(uid=179806, iid=928, r_ui=5.0, est=4.577860170123957, details={'was_impossible': False}),
 Prediction(uid=141630, iid=3161, r_ui=4.5, est=4.152369442111097, details={'was_impossible': False}),
 Prediction(uid=119416, iid=39, r_ui=3.0, est=3.60741988439002, details={'was_impossible': False}),
 Prediction(uid=97025, iid=2137, r_ui=5.0, est=3.9238760556936843, details={'was_impossible': False}),
 Prediction(uid=126110, iid=58347, r_ui=3.5, est=3.3913314133973924, details={'was_impossible': False}),
 Prediction(uid=92627, iid=2329, r_ui=4.0, est=4.136110337677545, details={'was_impossible': False}),
 Prediction(uid=26624, iid=39231, r_ui=2.5, est=2.7161304041661163, details={'was_impossible': False}),
 Prediction(uid=137180, iid=314, r_ui=4.0, est=3.581462114203363, details={'was_impossible': False}),
 Prediction(uid=14794, iid=5009, r_ui=3.0, est=3.627833234710116, details={'was_impossible': False}),
 Prediction(uid=196196, iid=42418, r_ui=3.0, est=3.9170757446031734, details={'was_impossible': False}),
 Prediction(uid=147755, iid=3071, r_ui=4.5, est=3.445755875377694, details={'was_impossible': False}),
 Prediction(uid=207297, iid=3998, r_ui=3.0, est=3.3753464521031535, details={'was_impossible': False}),
 Prediction(uid=33263, iid=3755, r_ui=1.5, est=1.4827852845309333, details={'was_impossible': False}),
 Prediction(uid=165825, iid=235, r_ui=4.0, est=3.6176106147108005, details={'was_impossible': False}),
 Prediction(uid=156570, iid=110, r_ui=5.0, est=4.292496368973821, details={'was_impossible': False}),
 Prediction(uid=126126, iid=724, r_ui=2.0, est=2.4720426082403546, details={'was_impossible': False}),
 Prediction(uid=249630, iid=89759, r_ui=4.0, est=4.023629772887629, details={'was_impossible': False}),
 Prediction(uid=232441, iid=434, r_ui=2.5, est=2.6464851584413815, details={'was_impossible': False}),
 Prediction(uid=218143, iid=7445, r_ui=3.0, est=3.8807089408889626, details={'was_impossible': False}),
 Prediction(uid=10884, iid=68358, r_ui=4.5, est=3.805368645451076, details={'was_impossible': False}),
 Prediction(uid=25621, iid=8690, r_ui=3.0, est=3.8581422871260007, details={'was_impossible': False}),
 Prediction(uid=164343, iid=106920, r_ui=4.0, est=4.372466447472837, details={'was_impossible': False}),
 Prediction(uid=31866, iid=2054, r_ui=3.0, est=2.2718621392918554, details={'was_impossible': False}),
 Prediction(uid=155608, iid=56885, r_ui=4.0, est=3.98967602021723, details={'was_impossible': False}),
 Prediction(uid=264818, iid=1207, r_ui=4.5, est=4.195552934466132, details={'was_impossible': False}),
 Prediction(uid=123484, iid=1408, r_ui=2.5, est=2.7919344997386384, details={'was_impossible': False}),
 Prediction(uid=255173, iid=2797, r_ui=2.0, est=2.794219815796337, details={'was_impossible': False}),
 Prediction(uid=214479, iid=914, r_ui=4.0, est=4.522828402022017, details={'was_impossible': False}),
 Prediction(uid=230302, iid=69644, r_ui=5.0, est=4.343036738146551, details={'was_impossible': False}),
 Prediction(uid=70990, iid=2542, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=130147, iid=53322, r_ui=3.0, est=3.273088241566468, details={'was_impossible': False}),
 Prediction(uid=255695, iid=98809, r_ui=5.0, est=4.435920062941776, details={'was_impossible': False}),
 Prediction(uid=68268, iid=1293, r_ui=4.0, est=3.717152394012213, details={'was_impossible': False}),
 Prediction(uid=62303, iid=1407, r_ui=4.0, est=4.012702034306106, details={'was_impossible': False}),
 Prediction(uid=269622, iid=102407, r_ui=3.5, est=3.686869364873079, details={'was_impossible': False}),
 Prediction(uid=239091, iid=136020, r_ui=1.5, est=1.3532791928023657, details={'was_impossible': False}),
 Prediction(uid=7196, iid=1777, r_ui=3.5, est=3.653015219051097, details={'was_impossible': False}),
 Prediction(uid=188637, iid=4733, r_ui=4.0, est=3.784243201545878, details={'was_impossible': False}),
 Prediction(uid=36521, iid=230, r_ui=4.0, est=3.558318651343719, details={'was_impossible': False}),
 Prediction(uid=31085, iid=102481, r_ui=4.0, est=3.5819308794151516, details={'was_impossible': False}),
 Prediction(uid=124914, iid=104841, r_ui=3.5, est=3.52973304809159, details={'was_impossible': False}),
 Prediction(uid=113160, iid=6664, r_ui=3.5, est=3.4608189069292505, details={'was_impossible': False}),
 Prediction(uid=179792, iid=6356, r_ui=4.5, est=3.742497129906904, details={'was_impossible': False}),
 Prediction(uid=39055, iid=1266, r_ui=4.0, est=4.184339577561439, details={'was_impossible': False}),
 Prediction(uid=227595, iid=3271, r_ui=2.0, est=3.12065341567664, details={'was_impossible': False}),
 Prediction(uid=98355, iid=5026, r_ui=4.0, est=3.5826118491331163, details={'was_impossible': False}),
 Prediction(uid=33130, iid=788, r_ui=2.5, est=2.9590374178429553, details={'was_impossible': False}),
 Prediction(uid=255913, iid=1597, r_ui=4.0, est=4.283994367585674, details={'was_impossible': False}),
 Prediction(uid=74207, iid=112290, r_ui=5.0, est=4.142199924049743, details={'was_impossible': False}),
 Prediction(uid=73517, iid=2393, r_ui=2.5, est=2.9679738308223236, details={'was_impossible': False}),
 Prediction(uid=34105, iid=1220, r_ui=4.0, est=2.9374232409531404, details={'was_impossible': False}),
 Prediction(uid=40244, iid=68157, r_ui=3.5, est=4.337178408840043, details={'was_impossible': False}),
 Prediction(uid=162435, iid=26318, r_ui=4.5, est=4.019725723621703, details={'was_impossible': False}),
 Prediction(uid=146263, iid=78574, r_ui=2.5, est=2.786049052877801, details={'was_impossible': False}),
 Prediction(uid=15354, iid=141, r_ui=3.0, est=4.132188402086487, details={'was_impossible': False}),
 Prediction(uid=133936, iid=1961, r_ui=3.5, est=3.3071126361069614, details={'was_impossible': False}),
 Prediction(uid=199152, iid=4889, r_ui=4.0, est=3.9414133537962193, details={'was_impossible': False}),
 Prediction(uid=121363, iid=6542, r_ui=3.5, est=3.925792999149074, details={'was_impossible': False}),
 Prediction(uid=79621, iid=32296, r_ui=1.5, est=1.6438424783358414, details={'was_impossible': False}),
 Prediction(uid=40651, iid=6638, r_ui=4.5, est=4.324284492049782, details={'was_impossible': False}),
 Prediction(uid=107527, iid=296, r_ui=3.0, est=3.4835342744112525, details={'was_impossible': False}),
 Prediction(uid=134154, iid=2371, r_ui=3.5, est=2.9908652679679504, details={'was_impossible': False}),
 Prediction(uid=78228, iid=68157, r_ui=4.0, est=3.8032081199182466, details={'was_impossible': False}),
 Prediction(uid=199280, iid=5577, r_ui=4.0, est=3.651060333581521, details={'was_impossible': False}),
 Prediction(uid=131076, iid=74458, r_ui=4.0, est=3.853267171162173, details={'was_impossible': False}),
 Prediction(uid=55919, iid=1092, r_ui=2.0, est=2.0269366699721325, details={'was_impossible': False}),
 Prediction(uid=179726, iid=4076, r_ui=2.0, est=2.829859325675028, details={'was_impossible': False}),
 Prediction(uid=15124, iid=4306, r_ui=4.5, est=4.424978543854339, details={'was_impossible': False}),
 Prediction(uid=228147, iid=2287, r_ui=3.0, est=3.9173709158343435, details={'was_impossible': False}),
 Prediction(uid=193073, iid=1704, r_ui=2.0, est=3.892451310456128, details={'was_impossible': False}),
 Prediction(uid=167231, iid=3510, r_ui=4.0, est=3.3924623396243034, details={'was_impossible': False}),
 Prediction(uid=87913, iid=457, r_ui=5.0, est=4.1060846198807734, details={'was_impossible': False}),
 Prediction(uid=31819, iid=4477, r_ui=1.0, est=1.9866652724973404, details={'was_impossible': False}),
 Prediction(uid=83895, iid=8973, r_ui=4.5, est=4.196678999084203, details={'was_impossible': False}),
 Prediction(uid=27100, iid=4958, r_ui=2.5, est=3.0496746492782996, details={'was_impossible': False}),
 Prediction(uid=84654, iid=904, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=170983, iid=3175, r_ui=4.0, est=3.7444972308868554, details={'was_impossible': False}),

In [21]:
#Predict the rating of User 10 for Movie ID 34. (The rating is the 4th element in the array for the chosen user)
prediction = svd.predict(10,34)[3]  
print(prediction)

4.273112860672884

In [37]:
user_rating = []

for i in mov_ids:
    predict = svd.predict(10,i)[3]
    user_rating.append(predict)

In [39]:
user_rating

[4.297400028649263,
 3.8344876957879985,
 4.4664673849285865,
 4.298657126380337,
 4.113894198517546,
 4.196496205728968,
 4.619436140221071,
 4.354923908440194,
 4.429357589910895,
 4.32602414010134,
 4.216744510067108,
 3.77572773026816,
 4.2885659652459935,
 4.178900976415933,
 4.593743005569792,
 4.298233439471123,
 4.120953279108236,
 4.2548337175353925,
 4.314782486250392,
 4.205684296962398,
 3.896380581537777,
 4.135449341889914,
 3.844664767697621,
 4.183042078922433,
 4.289666691375968,
 4.335188928341973,
 4.250604771828811,
 3.504205024226399,
 3.5516899033296356,
 3.843193081466808,
 4.004866300737615,
 3.2232207079974846,
 3.606435364226549,
 3.6052241294862264,
 4.346108828684574,
 4.052514399120412,
 3.987784055437907,
 3.7023291346871843,
 4.109498074294657,
 3.9683908328490936,
 2.8183358781930554,
 4.055280426493969,
 3.8020597861992402,
 3.974003132141661,
 4.302065527547444,
 3.887575001885009,
 3.8297280042614537,
 3.1456198201684096,
 3.616744612073713,
 3.826021984054149,
 3.8103253145120255,
 4.388491834088745,
 3.8505176285747256,
 4.107791858616535,
 4.293389855609726,
 3.636778695548297,
 3.3184151559321906,
 4.126463253561394,
 3.2074247418136568,
 4.389413904471118,
 3.7299648887825025,
 2.9819553432711277,
 3.9374248897730424,
 3.9793653201711807,
 2.8642203835224973,
 3.84304720362235,
 3.969191036196281,
 3.8517141394215773,
 3.176778247422612,
 3.5017749600125967,
 2.8717727409161338,
 4.215519805808873,
 4.137271265018153,
 3.7284013633015434,
 3.690391225915917,
 3.359538562598464,
 3.7734462900474446,
 4.1807131552031755,
 3.9283873425066185,
 3.9639874508104684,
 2.850310360641766,
 3.1655810173711014,
 4.121823261364835,
 3.928543912523761,
 3.5523424422573546,
 3.3204381311155795,
 3.655700774822089,
 3.8075420135940403,
 3.0499160125873974,
 3.8726221809197843,
 4.407445455354629,
 3.2273457568350623,
 3.834501898107978,
 3.138760158467668,
 3.8970885526378747,
 4.0539953781027185,
 3.710109782422661,
 3.798262160790253,
 4.438433346863117,
 3.259479045188288,
 3.9562853923898693,
 3.811793167774775,
 3.9622508751581313,
 3.594325005115184,
 2.8598093777644036,
 3.399739689093465,
 3.288546559778457,
 4.018336528638696,
 3.488610786993853,
 3.9857369819204465,
 4.007499579847839,
 4.2359253957635765,
 3.546707195347041,
 3.8633931822342773,
 3.055213157863778,
 4.172959696306304,
 4.284407570833764,
 4.267755148458535,
 4.405206428679681,
 4.413355064852124,
 4.357764898780119,
 4.3255665550482485,
 4.260137248543591,
 3.9467787511295653,
 4.0248303240051095,
 4.220195264075701,
 3.9959771980117056,
 3.871144718375533,
 4.263856589670342,
 2.3644783412382617,
 3.646121715662211,
 3.410634112081608,
 3.8550461718180014,
 3.1400522332743073,
 4.297041960384323,
 3.703915702609788,
 3.984554714157234,
 3.940152179660003,
 3.891746612352626,
 4.402159283563631,
 4.713420056212004,
 4.671363542402028,
 4.501486849924402,
 3.576590844198748,
 4.249248207446985,
 3.7785795166933696,
 4.573165465982006,
 4.286773742453621,
 4.528224401234546,
 3.8768695453314534,
 4.073351925769826,
 4.590096166500355,
 3.5277306564490956,
 4.4429931828361395,
 4.223544228703257,
 3.8883429248757877,
 4.478804108397365,
 4.028571386647443,
 4.2280362261817475,
 3.5450440411287136,
 4.166662296838838,
 3.723143909841262,
 4.342302019094835,
 4.235305988846019,
 4.138638803836126,
 4.197749597622539,
 4.052039313243454,
 3.6718993268461375,
 4.211330295971637,
 4.527329786751571,
 3.4616233090517943,
 4.562681729446423,
 4.005536232940087,
 4.332217174874674,
 3.678108549729816,
 4.140283343755961,
 4.156808671234819,
 4.5611086514618675,
 4.256906062272854,
 4.008831247748612,
 4.249119136983018,
 3.7402561272478145,
 4.45353016824058,
 4.363067048623857,
 2.565659146747695,
 4.172226969113104,
 3.312952261732762,
 3.243770148720639,
 3.3610237609298577,
 4.086174532338165,
 2.477072450634192,
 3.7822879184029548,
 3.6015620566534774,
 2.8068493798442167,
 4.111889100030394,
 3.428793564814327,
 4.189578918703936,
 3.597509912018843,
 3.1934281189699036,
 4.318449265017779,
 3.866535643888207,
 4.0789167430350215,
 4.024912346754117,
 3.5588780593815503,
 4.320880631929682,
 4.241716749075817,
 3.7608575209063195,
 3.7825192160631342,
 3.5285879404734426,
 2.7297202420863877,
 2.3898384197554696,
 3.3058245229692824,
 2.882138818222401,
 3.8056331345730463,
 3.843786098429798,
 3.189371004959153,
 3.3596925293269084,
 3.147345895110311,
 3.702693526637341,
 4.462257729494894,
 3.4001746660803764,
 3.6010504789751066,
 3.675738035573488,
 3.2710071697172283,
 4.100833369702322,
 3.8171821662889873,
 3.665145384619479,
 3.3692600729240363,
 3.4667877462646106,
 3.5874931681972475,
 3.951164699089366,
 3.7921858710105996,
 4.163041537269733,
 4.097498987258812,
 3.302462648707676,
 3.301864106740495,
 3.381813793550768,
 3.677421119928675,
 4.286511747277809,
 3.68652710900889,
 3.366477715224228,
 4.416338863266369,
 3.8433686002027083,
 3.5505036339768443,
 3.224522583637357,
 4.192171494955211,
 4.025749201535833,
 4.0502203332851625,
 3.2086504496590535,
 4.039996840303806,
 3.9565334057781683,
 3.6383904266988085,
 3.173662527349672,
 3.7415912029169798,
 3.531311697377645,
 3.8907273491442793,
 3.4116008427125077,
 3.679029777625741,
 3.8902379467267947,
 3.3568020843574904,
 3.6500438581289263,
 3.498430798920556,
 3.8098310470607,
 3.112825898142955,
 3.635073173463981,
 3.135803879093357,
 3.15664912250537,
 3.1443625647518565,
 3.654542985635043,
 3.69857714381441,
 3.877300044712663,
 4.1165707671414955,
 3.780120423000296,
 4.415986806917935,
 3.465783164365458,
 3.986814833497928,
 3.418497979842826,
 3.5401652114368933,
 4.120156779569212,
 3.8914619159252646,
 3.5483252666317417,
 3.301244782438588,
 3.8380381245924258,
 4.198574743362891,
 4.366994590760818,
 3.8342800392611043,
 4.206664658681553,
 3.2901528301393173,
 3.6756833009001726,
 3.820881578793771,
 3.56010302035971,
 4.211424964872625,
 4.188295357448578,
 3.811791081829738,
 4.294259425363218,
 4.307507319840362,
 4.278845495258446,
 3.1861254670219203,
 4.119063597270373,
 3.182136427552031,
 4.056797456162289,
 3.471727875006141,
 3.6371156533341824,
 4.4387453291185865,
 3.850747335605045,
 3.635733936208399,
 3.942837781161868,
 3.6497912414233498,
 3.9225974966706754,
 3.950452404561963,
 3.8121056840585004,
 4.035046795509029,
 4.131667965406032,
 4.163606588981095,
 3.695662669779411,
 3.68169646366741,
 3.4291015217841876,
 3.866947240373838,
 4.51146080353233,
 4.2585378705686185,
 3.561734066088358,
 3.7095486300200275,
 3.5755763365673063,
 3.876758505012517,
 4.147582117009792,
 3.8260646234116953,
 3.877676063861622,
 4.019617541369816,
 3.6188577418215315,
 3.7530443061350955,
 3.8773998655824826,
 3.746146029291032,
 3.959605727004548,
 4.374477938680987,
 4.3638998772325,
 3.594627309879066,
 3.2206243595001935,
 4.004751681775795,
 3.815293640155877,
 4.411408403625279,
 3.435507793894118,
 3.4352710142001817,
 4.015781433252789,
 3.7667560335257093,
 4.120247716855558,
 4.001754622540611,
 4.435791889930724,
 4.041520026453141,
 3.851390078194809,
 3.5491899337771655,
 4.2039664395088785,
 3.9552767629676593,
 3.9400747752044274,
 3.6779421872311193,
 4.515234493202253,
 4.406183502372172,
 3.555572563411788,
 3.6554165962365657,
 3.702048774787883,
 4.170138239686762,
 3.8887416390231695,
 4.1044768230871425,
 3.7726810659994703,
 3.8346726325691356,
 3.8738843235784888,
 4.370841381211639,
 4.411269267390076,
 2.9126294296627706,
 2.8626055259298235,
 3.9425689518619986,
 3.886176842973069,
 3.625439681771616,
 3.4599003082328585,
 4.398516110868789,
 4.338676153402836,
 3.266483110776551,
 2.617048471546105,
 4.132728323852986,
 4.048009353358169,
 3.927672230828947,
 4.2572055980609615,
 3.4534515088560482,
 4.261549092010264,
 3.8786413389765544,
 4.019820361371879,
 3.728574421435147,
 3.7611798627451174,
 3.4484802169496516,
 3.675414113921241,
 3.845390644007658,
 3.436671457519598,
 3.5626028335116406,
 3.4193457171530297,
 2.7978588364027774,
 4.32546818618329,
 4.3100904601735275,
 3.2576043440356286,
 3.912674063507079,
 3.7638083597489516,
 3.9445943029037207,
 3.9743968129898146,
 4.09859155532619,
 3.689287505343761,
 4.298351827794422,
 3.774171014775325,
 3.151824812413945,
 3.5751136767267333,
 4.066861629467839,
 3.634550607767079,
 4.1191207449770575,
 4.271956321127877,
 3.435834743175179,
 4.126698632590853,
 4.101029937072226,
 4.274355479354787,
 3.7939249558033965,
 3.738019814047374,
 4.08845155908665,
 3.920202258933682,
 4.100206499153941,
 3.8253787677297835,
 4.137108166737222,
 3.475616730963031,
 3.640576209368181,
 3.472461830245226,
 3.059985526963798,
 3.6601408636215904,
 3.755146018207381,
 3.6236684310971063,
 3.5668425883306005,
 3.7982457957910842,
 3.2740551496291896,
 4.13201681814208,
 3.9122646387347815,
 3.6887413816682266,
 3.8184476497791646,
 3.9864424688581233,
 3.7070381602195406,
 3.8200693931246956,
 3.643125475032938,
 4.047990742247676,
 3.453901959668122,
 3.576827543744706,
 3.587064514327153,
 4.041162626557511,
 4.199801144251069,
 3.817505247713273,
 4.001506909351952,
 4.06618625977395,
 3.4330545006509716,
 3.8395277322387864,
 4.044414418229777,
 3.9326007566421772,
 4.053091083420649,
 3.8704804068136833,
 3.8817423185954842,
 3.97734058414063,
 3.674918206162605,
 4.29040001458523,
 4.392854610310344,
 3.8766920949186034,
 3.3786528832888147,
 3.4824156171030882,
 3.4199732540597094,
 4.033517808879908,
 3.7714233320013646,
 4.043855049702174,
 3.8565558688252213,
 3.806384461799999,
 3.845158593222105,
 4.001402338377127,
 3.469508875608476,
 4.168562006605986,
 3.9203200236165707,
 4.083573068635354,
 3.611592645015688,
 3.562308855173438,
 4.1998517250516665,
 3.9950975690012105,
 3.9075019709718504,
 3.851757416100071,
 3.5681244139401747,
 3.7501897925945005,
 3.7243022653641638,
 3.5272989210089025,
 3.630563003485837,
 4.0663352726492,
 4.063015352104758,
 4.181120144422431,
 4.03255629260623,
 4.2337944716333755,
 3.8549092488388754,
 3.99391956954765,
 3.808143817834346,
 3.8815721006985684,
 3.7484195793936426,
 3.70571085046992,
 3.8361107770742096,
 3.553022572408301,
 3.9973340342902786,
 3.472557100341386,
 3.5893907863068346,
 3.5909344332513276,
 3.6933108066536318,
 4.051082678049557,
 4.195132355822205,
 4.019130301798784,
 3.2862480618614547,
 3.5728638983367427,
 3.170731704189318,
 3.6745034091028326,
 3.7463908984183947,
 3.520881682172291,
 3.9227550760773244,
 3.5366145497689603,
 3.353536578873891,
 4.295455595685024,
 4.355398301081017,
 3.5880047422781356,
 3.096330893305906,
 4.204690729151352,
 3.737889118762957,
 3.9929597190331667,
 3.3651423969170957,
 4.171162982959133,
 4.007127816269125,
 3.5883259296375063,
 3.9982919624138136,
 3.9266665009397643,
 3.6388639979302333,
 3.587583532850264,
 4.086853728682056,
 3.5483064983063026,
 4.096246953497317,
 3.787730065491863,
 3.8857893724121757,
 4.03796629875828,
 3.993564163166343,
 4.588809454218744,
 3.5319867489509535,
 4.244370883000568,
 4.125824014636455,
 4.087071954994885,
 4.186543321976986,
 3.8423636865061215,
 3.1402325560440767,
 3.848291480321668,
 3.7518947084112746,
 3.8961402887940197,
 3.9254495672208765,
 3.658211184862156,
 3.8812716984529114,
 3.599638791680637,
 3.729946275086482,
 3.559886369254601,
 3.3490823960060685,
 3.9025592139448317,
 3.7154490096950523,
 4.10584849262495,
 3.640545963536549,
 3.8549237316539755,
 3.9261404427145417,
 3.778107795098552,
 3.4777976007740814,
 3.9089423734666084,
 3.7029323522662057,
 4.181719769510479,
 3.884374860073077,
 4.133578948750189,
 3.7790000403766753,
 3.646748838189942,
 3.6335620026039845,
 3.8718924536946413,
 3.7169357425053695,
 3.8003227478951547,
 3.7936762460749383,
 3.6675218251803208,
 3.732958430211176,
 4.272286173881738,
 3.887775095153018,
 3.9832427142899567,
 3.6210170801993695,
 3.7597447578754357,
 4.251149418923926,
 4.03949328307979,
 3.8491041415072687,
 3.9427759035067598,
 4.291084757852518,
 4.35396948929253,
 4.436772402007495,
 4.083454241761614,
 4.017819772732357,
 4.136143933438707,
 4.155374653164654,
 4.130945283408583,
 3.838125875552743,
 4.356224202921068,
 3.840740719392996,
 4.314788855290171,
 4.329093451554694,
 4.163502628532945,
 4.223289943689475,
 3.59672564089592,
 4.311477378265429,
 4.393634585233415,
 4.253857478446838,
 4.481035050547065,
 4.088717424995306,
 4.030970798049253,
 4.043764154698144,
 3.836173436789532,
 3.7793581752767604,
 4.240670536709421,
 4.290286819751882,
 4.047362898329322,
 4.1428821220081655,
 4.373060655240678,
 4.219441099438318,
 4.013929466630288,
 4.193809627153118,
 4.027233170113567,
 3.8451567459481817,
 4.311303528614528,
 4.321542783619047,
 4.055117210861112,
 4.174247422091746,
 4.003209002825751,
 4.158304617001564,
 3.8720920855103653,
 4.054374753143012,
 4.204324252292384,
 3.9908431565892215,
 3.8653642467487943,
 3.906059770088205,
 4.076959346637044,
 3.639652523520783,
 4.102698877989389,
 3.9250569157502873,
 3.9872362335745755,
 3.860848340340331,
 4.033570475199947,
 3.533311846386445,
 3.5661917994790295,
 4.05828205888248,
 3.428327519942947,
 4.147101116313368,
 4.188268824358022,
 3.542717286311509,
 3.6205392634937748,
 4.30489157451219,
 3.9742476052151954,
 3.61341177822233,
 3.911084376870765,
 4.171893538932312,
 3.3332325758559325,
 4.01906124390238,
 3.5899164648168926,
 3.8044808392177125,
 3.6946695272477603,
 3.3631348670794363,
 4.599501617650739,
 3.813997007811819,
 3.8225270077890467,
 4.477541581966837,
 3.5520392531248186,
 3.8668583856453522,
 4.222376480774951,
 3.0599121624971453,
 3.3303755073474037,
 3.8018440547456067,
 3.830918418254384,
 3.783976558048441,
 3.7620004125039066,
 3.6657781296828706,
 4.055385246634705,
 4.257661152149862,
 3.7019878507413106,
 3.7053332744376,
 3.5803437182015996,
 3.567796589194081,
 2.9906856535984065,
 3.786224779543114,
 3.1839643260160884,
 3.9917243037256696,
 3.411400527750079,
 3.456917703808405,
 3.6681925600430145,
 4.200717557358393,
 3.759583055583403,
 4.110300944855629,
 3.341974413230076,
 3.5837448650673465,
 3.206634103690241,
 4.077283161103104,
 3.7074718562020306,
 3.797662625639583,
 3.750573737105035,
 3.888033827501384,
 3.3094261202360853,
 3.651220992850202,
 3.6843344680036294,
 3.1208245177513234,
 3.603661760448687,
 3.9861615702436364,
 3.636854819489237,
 3.7392678142924543,
 3.1458471000809345,
 4.359619796721645,
 3.975062197014587,
 3.7839774239667032,
 3.550890429735802,
 3.110307408061424,
 3.639259333632224,
 4.033005049305513,
 3.9696795032305636,
 3.177905620693631,
 3.7047751129029445,
 3.7878681422722327,
 3.9762245502926086,
 4.15684813815358,
 3.516761606112878,
 3.766110190279622,
 3.8838499581737875,
 3.8940262311324085,
 3.891876713838398,
 3.512806369606296,
 3.3821376028608414,
 3.8340044060718097,
 4.0416646957661,
 3.550429269354771,
 3.9282961068021254,
 4.325128061958794,
 4.273912540133314,
 4.04827715643406,
 3.299770779779916,
 3.822957345763381,
 3.186367381650182,
 4.131964569322643,
 4.288712094083942,
 4.444501036819492,
 4.05107786677229,
 3.769438578062725,
 4.266142994627434,
 4.3255346513847535,
 4.219040529307935,
 4.045973603830784,
 3.6187177211596544,
 3.777664006122184,
 4.079556885224935,
 4.151081676586966,
 4.122883368003281,
 3.334560727684165,
 3.7275368909328184,
 3.8894202350106535,
 3.7233324964180983,
 3.8562133755507864,
 4.083933531076849,
 3.274757988668353,
 4.100486759760063,
 3.896926212895689,
 3.6375867653222835,
 4.202180441044089,
 4.396391133473515,
 3.5001273469086667,
 3.877540050605883,
 3.988785944701057,
 3.9658866515058366,
 4.027275482173069,
 4.372110241866491,
 4.030120915385832,
 3.9503084765170513,
 3.5172051653891003,
 4.118106427038047,
 3.9412636078751127,
 3.525551585029899,
 4.355278832864715,
 4.074905053044082,
 4.003761333832081,
 3.936835973616543,
 4.284266581274283,
 3.9450237495192764,
 4.163516785194749,
 4.287736081307525,
 4.029341953602373,
 4.073959980348377,
 3.7498773626567816,
 4.198740328433429,
 4.497265859473293,
 4.228692591713852,
 4.083996950789608,
 4.01750181296082,
 4.168547800024998,
 4.054432581205838,
 4.394394118330149,
 4.078488696890799,
 4.143761243263558,
 4.31026717429583,
 3.9254071313528267,
 4.087817067461038,
 3.9220968930782862,
 4.324614922694745,
 4.167392730032866,
 4.002625285079754,
 4.061257017814776,
 3.701534598653459,
 4.015386905192737,
 4.103100302075968,
 4.249649215596063,
 4.108357686022775,
 3.8771689410878802,
 4.249472585922036,
 3.9447845104651664,
 3.9727685296047603,
 4.314893094926436,
 3.716812937574315,
 4.095302357792801,
 4.2206518900445955,
 4.03459694830717,
 3.9997972719736534,
 4.572790920544311,
 4.061194784456565,
 4.116280585563839,
 4.076585885258656,
 4.313878716790555,
 4.082626094088675,
 4.276286928232883,
 4.207952321371461,
 4.018128931259545,
 4.039333073035844,
 4.23729542403378,
 4.316624808924409,
 4.07133834328595,
 4.047088034022444,
 4.282734710135139,
 4.233313112066795,
 4.217389691298942,
 4.2984251842066765,
 4.155691773924933,
 4.0400817437133,
 3.863721613834721,
 4.507903148322944,
 3.754095378433021,
 4.227459121524581,
 4.007064268327057,
 4.069157776686757,
 4.308773760997909,
 4.135251956479303,
 4.352414413617684,
 4.314072362474243,
 4.121207458423811,
 4.122044005858901,
 4.186444330116473,
 4.012188436008492,
 3.8843104192040627,
 4.345038049131938,
 4.019387442746703,
 3.9394738972011196,
 4.09313457067117,
 4.31568899022158,
 4.170607175575173,
 3.9843003625516995,
 4.056050309378658,
 4.072519451983225,
 4.020780364362206,
 3.6967779730839023,
 3.9637875387189463,
 3.4295698267368793,
 4.274127816372426,
 3.632090894241762,
 3.6444139079952955,
 4.190117994701355,
 3.220641750492267,
 3.384886634748194,
 3.577166608958673,
 3.568071766035515,
 3.7249503403236592,
 4.404574886671518,
 3.5341942820569376,
 3.605891562703034,
 3.706649671189709,
 3.4224016631002487,
 3.9623444235729957,
 3.7463676793659255,
 3.73007264004882,
 4.050583651460421,
 3.562813831770633,
 3.6598776250169327,
 4.200826881969567,
 4.166200124813163,
 3.511149302221292,
 3.8219797079832407,
 3.1384206847580365,
 3.5983175197278934,
 3.75083993817511,
 3.404958112474221,
 4.033473148756423,
 3.6352426205259314,
 4.088256706495464,
 3.864458323681686,
 3.3895641866498294,
 3.921092921795375,
 3.5183978152895135,
 3.385260577317082,
 3.497835528586266,
 4.086988422879037,
 4.67274580642144,
 3.5788117548692133,
 3.208665500550754,
 3.8467129758413123,
 3.9572589348814833,
 3.5102083540938436,
 3.497778090760284,
 3.2381414224846203,
 4.087676775254631,
 3.6048791040092705,
 3.988324049480453,
 3.5001163696000988,
 4.138585546826842,
 2.710404993069695,
 3.6879549479547014,
 3.8020700718961544,
 4.254193782406078,
 3.525436294933172,
 3.847298077351187,
 4.012614118747242,
 3.5606060135905286,
 4.009242531938607,
 4.065137986069468,
 3.9861103216884266,
 3.980245212878128,
 3.674131570015852,
 3.6034115233150246,
 3.7338966914804286,
 3.563589757446656,
 3.702132079447657,
 3.9246575992566273,
 4.2504262042440875,
 3.8424033190066504,
 3.8080380884369682,
 3.68360407156209,
 3.7956680456260634,
 3.57133250574301,
 3.5134191921632523,
 3.4543808462571235,
 4.0431642492551205,
 4.06163380389538,
 4.067403017011761,
 4.055096185580016,
 4.244920370101806,
 4.208723932176801,
 3.7802647762037083,
 3.882905254086861,
 4.086051911353007,
 3.663651256320079,
 3.9423068398948033,
 4.390601882723294,
 3.2824799755845877,
 3.9866893170807303,
 3.9150083219610945,
 3.660228327323433,
 3.850759567226038,
 4.1646855652147465,
 3.1122671381306453,
 3.6922797617158643,
 3.9076079737363787,
 2.954887370553409,
 3.7154806462603345,
 3.6010371770948852,
 2.8685229073008465,
 3.564112688238787,
 3.8597898010671394,
 3.426623913648339,
 2.6420559299452733,
 3.520459922924859,
 3.6566450525906564,
 3.681907105404682,
 3.409694348448784,
 3.834409602167157,
 3.7492253184754567,
 3.183716988466938,
 3.6352815386284365,
 2.822896575907726,
 3.531155671995178,
 4.172858566253711,

In [41]:
len(user_rating)

45115

In [43]:
df_recommend = pd.DataFrame(list(zip(mov_ids, 
                                     user_rating)), columns = ["movie_id","Ranking"])

In [45]:
df_recommend

       movie_id   Ranking
0           110  4.297400
1           147  3.834488
2           858  4.466467
3          1221  4.298657
4          1246  4.113894
...         ...       ...
45110    159050  3.849307
45111    159053  3.819775
45112    165649  3.819775
45113    171051  3.805559
45114    171221  3.819775

[45115 rows x 2 columns]

In [47]:
df_recommend = df_recommend.sort_values(by=['Ranking'], ascending=False,ignore_index=True)

In [49]:
df_recommend.head(30)

    movie_id   Ranking
0     174053  4.857627
1     170705  4.805146
2      98491  4.734298
3     159817  4.731033
4        318  4.713420
5     171011  4.688050
6     120625  4.685690
7      73881  4.673063
8      31658  4.672746
9       2571  4.671364
10    136445  4.665210
11    159819  4.656444
12    130970  4.645830
13    106334  4.640261
14     92535  4.634655
15    147286  4.631627
16    140265  4.626027
17      2762  4.619436
18    143990  4.614004
19     69122  4.611082
20     95654  4.605251
21     72356  4.601895
22      1704  4.599502
23    100044  4.595927
24     58559  4.593743
25     79091  4.593028
26      6377  4.590096
27        50  4.588809
28    139090  4.588030
29    147250  4.587277

In [29]:
df_recommend['movie_id'][0]

7153

In [30]:
grab = []
for i in range(0,5):
    grab.append(df_recommend["movie_id"][i].astype('str'))

print(grab)

['7153', '318', '170705', '142115', '100553']

In [31]:
# If the datasets matched up with the previous file, (or you had movies names with their ID keys)
# could use the index numbers to grab the movie names from the original Metadata dataset

print(df_movie_names["title"][df[df["id"]=="7153"].index])
print(df_movie_names["title"][df[df["id"]=="318"].index])

NameError: name 'df_movie_names' is not defined