# <center> Module 6: Recommender Systems</center>
## <center> Collaborative Filtering: Memory Based Recommenders <br> MovieLens Movies Database </center>
<center>by: Nicole Woodland, P. Eng. for RoboGarden Inc. </center>

---

#### Ask the Right Question:

In this example, we have a database of Users and the ratings they have given to various movies. <br> Can we use this data to make movies recommendations to the user?

### <font color='blue'> Download the Dataset </font>
Download the Dataset from the following link: <br>
https://www.kaggle.com/rounakbanik/the-movies-dataset?select=movies_metadata.csv

In [3]:
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

<font color = "blue"> Read the dataset into the Pandas Data Frame!

In [6]:
#Load the small dataset
#ratings = pd.read_csv("ratings.csv")
import pandas as pd
import numpy as np
ratings = pd.read_csv("../ratings_small.csv")

In [10]:
ratings.head(25)

    userId  movieId  rating   timestamp
0        1       31     2.5  1260759144
1        1     1029     3.0  1260759179
2        1     1061     3.0  1260759182
3        1     1129     2.0  1260759185
4        1     1172     4.0  1260759205
5        1     1263     2.0  1260759151
6        1     1287     2.0  1260759187
7        1     1293     2.0  1260759148
8        1     1339     3.5  1260759125
9        1     1343     2.0  1260759131
10       1     1371     2.5  1260759135
11       1     1405     1.0  1260759203
12       1     1953     4.0  1260759191
13       1     2105     4.0  1260759139
14       1     2150     3.0  1260759194
15       1     2193     2.0  1260759198
16       1     2294     2.0  1260759108
17       1     2455     2.5  1260759113
18       1     2968     1.0  1260759200
19       1     3671     3.0  1260759117
20       2       10     4.0   835355493
21       2       17     5.0   835355681
22       2       39     5.0   835355604
23       2       47     4.0   835355552
24       2       50     4.0   835355586

In [17]:
mov_ids = ratings.movieId.unique()
print(mov_ids)
print(len(mov_ids))

[  31 1029 1061 ...  129 4736 6425]
9066

In [19]:
ratings.tail(10)

        userId  movieId  rating   timestamp
99994      671     5952     5.0  1063502716
99995      671     5989     4.0  1064890625
99996      671     5991     4.5  1064245387
99997      671     5995     4.0  1066793014
99998      671     6212     2.5  1065149436
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

## Create a Memory-Based Collaborative Filtering Recommender

In [22]:
# Preprocessing
ratings = ratings.drop('timestamp', axis = 1)

In [24]:
ratings

        userId  movieId  rating
0            1       31     2.5
1            1     1029     3.0
2            1     1061     3.0
3            1     1129     2.0
4            1     1172     4.0
...        ...      ...     ...
99999      671     6268     2.5
100000     671     6269     4.0
100001     671     6365     4.0
100002     671     6385     2.5
100003     671     6565     3.5

[100004 rows x 3 columns]

### Create the User-Item Matrix

In [31]:
user_item_m = ratings.pivot(index = 'userId', columns = "movieId", values = 'rating').fillna(0)
user_item_m

movieId,1,2,3,4,5,6,7,8,9,10,...,161084,161155,161594,161830,161918,161944,162376,162542,162672,163949
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
670,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
671,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Define similarity matrix

In [27]:
from sklearn.metrics.pairwise import cosine_similarity
X_user = cosine_similarity(user_item_m)
X_item = cosine_similarity(user_item_m.T)

In [28]:
print(X_user.shape)
print(X_item.shape)

(671, 671)
(9066, 9066)

In [50]:
print(len(X_user[0]))
X_user[0]

671

array([1.        , 0.        , 0.        , 0.07448245, 0.01681799,
       0.        , 0.08388416, 0.        , 0.01284289, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05938727,
       0.        , 0.02107287, 0.        , 0.08563118, 0.01656352,
       0.05733056, 0.0436822 , 0.07024269, 0.        , 0.01491541,
       0.00262104, 0.03501505, 0.        , 0.        , 0.06130103,
       0.02379292, 0.03170691, 0.00821267, 0.08459736, 0.13058496,
       0.01652849, 0.        , 0.03282542, 0.0203909 , 0.        ,
       0.06833225, 0.        , 0.04105418, 0.        , 0.        ,
       0.        , 0.        , 0.02081219, 0.07333877, 0.        ,
       0.        , 0.        , 0.        , 0.03782836, 0.        ,
       0.03844173, 0.06430548, 0.        , 0.01381982, 0.        ,
       0.01399113, 0.        , 0.        , 0.        , 0.        ,
       0.04528371, 0.        , 0.00203034, 0.        , 0.03191959,
       0.        , 0.        , 0.08815485, 0.        , 0.04607949,
       0.05055473, 0.05434844, 0.02342739, 0.00638392, 0.        ,
       0.00859143, 0.        , 0.02156587, 0.        , 0.        ,
       0.        , 0.00868171, 0.02296659, 0.        , 0.0369091 ,
       0.        , 0.        , 0.        , 0.02336634, 0.06935038,
       0.01409893, 0.        , 0.01113426, 0.01507229, 0.        ,
       0.        , 0.11061886, 0.04105543, 0.        , 0.06295552,
       0.        , 0.        , 0.        , 0.        , 0.01793091,
       0.01085366, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06418191, 0.10702625, 0.0285293 ,
       0.        , 0.        , 0.        , 0.        , 0.01861684,
       0.        , 0.        , 0.01375495, 0.        , 0.1128173 ,
       0.        , 0.        , 0.04536836, 0.01552579, 0.        ,
       0.        , 0.0237856 , 0.        , 0.        , 0.        ,
       0.03972436, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05662497, 0.        , 0.03714867,
       0.        , 0.01107776, 0.        , 0.01615124, 0.0547292 ,
       0.        , 0.01478723, 0.        , 0.        , 0.        ,
       0.01794253, 0.        , 0.        , 0.        , 0.03409791,
       0.        , 0.05243038, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02320688,
       0.        , 0.03256007, 0.02416268, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05175364,
       0.02407593, 0.        , 0.03402944, 0.        , 0.01577255,
       0.        , 0.        , 0.01902068, 0.        , 0.12264701,
       0.03295271, 0.05239205, 0.04105918, 0.01088565, 0.        ,
       0.        , 0.06477871, 0.        , 0.        , 0.        ,
       0.        , 0.15274613, 0.        , 0.        , 0.        ,
       0.02566508, 0.05341078, 0.01317318, 0.0893721 , 0.        ,
       0.        , 0.02125244, 0.        , 0.        , 0.02890549,
       0.        , 0.01880908, 0.        , 0.00838886, 0.        ,
       0.0167404 , 0.        , 0.024441  , 0.11257474, 0.        ,
       0.        , 0.08976054, 0.03849354, 0.        , 0.        ,
       0.01759041, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.03499459, 0.03093657, 0.        , 0.        ,
       0.        , 0.03406709, 0.03833662, 0.        , 0.        ,
       0.        , 0.03293479, 0.00914493, 0.01463585, 0.        ,
       0.        , 0.02565598, 0.        , 0.        , 0.        ,
       0.        , 0.01833513, 0.        , 0.        , 0.07111912,
       0.        , 0.        , 0.0171179 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08835959, 0.        , 0.        , 0.        , 0.08094778,
       0.04318461, 0.00879305, 0.03622283, 0.        , 0.05886316,
       0.        , 0.01821885, 0.01813161, 0.        , 0.0812857 ,
       0.04983508, 0.01492461, 0.        , 0.04555866, 0.01887164,
       0.        , 0.02952889, 0.        , 0.03439712, 0.03196288,
       0.        , 0.        , 0.04989034, 0.01350079, 0.        ,
       0.05781542, 0.        , 0.0100647 , 0.0556856 , 0.15752433,
       0.06084026, 0.05034743, 0.01320346, 0.        , 0.05814347,
       0.        , 0.        , 0.0287678 , 0.        , 0.05669426,
       0.04967354, 0.        , 0.        , 0.        , 0.37185158,
       0.0261166 , 0.        , 0.0331263 , 0.        , 0.04684663,
       0.        , 0.        , 0.        , 0.        , 0.07388513,
       0.        , 0.01929173, 0.02334196, 0.        , 0.        ,
       0.16281929, 0.03427715, 0.        , 0.02648466, 0.        ,
       0.06791871, 0.        , 0.        , 0.        , 0.0194026 ,
       0.01850539, 0.02797476, 0.01458012, 0.        , 0.01432797,
       0.        , 0.        , 0.05614964, 0.        , 0.04185099,
       0.00807456, 0.03088488, 0.08244055, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03436955,
       0.        , 0.04596723, 0.06811539, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06232238,
       0.02266094, 0.        , 0.        , 0.00906438, 0.        ,
       0.01245744, 0.1054804 , 0.02847007, 0.        , 0.04022741,
       0.09150085, 0.        , 0.        , 0.01662758, 0.02517686,
       0.        , 0.        , 0.04213583, 0.        , 0.        ,
       0.06198436, 0.        , 0.10709466, 0.03531453, 0.06687343,
       0.        , 0.00656062, 0.00865417, 0.        , 0.        ,
       0.        , 0.01075103, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.02856747, 0.02139239,
       0.        , 0.        , 0.05569804, 0.04632873, 0.        ,
       0.        , 0.        , 0.03188319, 0.        , 0.03661603,
       0.01431953, 0.        , 0.        , 0.03429513, 0.        ,
       0.0398459 , 0.        , 0.        , 0.01990771, 0.        ,
       0.03824504, 0.03485761, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07404574, 0.        , 0.        , 0.        ,
       0.        , 0.0418626 , 0.03261414, 0.        , 0.03343253,
       0.07414096, 0.        , 0.07315209, 0.        , 0.        ,
       0.04948608, 0.02354118, 0.0914953 , 0.        , 0.07930017,
       0.01603946, 0.0777233 , 0.        , 0.0094776 , 0.        ,
       0.        , 0.06519841, 0.        , 0.        , 0.01463942,
       0.01885025, 0.01363051, 0.        , 0.        , 0.11402063,
       0.        , 0.0219479 , 0.01908271, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01844544, 0.09022913, 0.        , 0.        , 0.0199359 ,
       0.        , 0.00579387, 0.        , 0.        , 0.05095534,
       0.        , 0.02320688, 0.        , 0.07430613, 0.0897871 ,
       0.03398825, 0.        , 0.        , 0.05074426, 0.        ,
       0.03089229, 0.        , 0.08338221, 0.01996347, 0.02990439,
       0.05584664, 0.01284349, 0.        , 0.        , 0.06978353,
       0.        , 0.05080105, 0.        , 0.06524185, 0.02819785,
       0.        , 0.0280646 , 0.07019961, 0.06007672, 0.        ,
       0.        , 0.04017221, 0.        , 0.10436802, 0.        ,
       0.        , 0.        , 0.        , 0.0127034 , 0.06277648,
       0.06160218, 0.05767321, 0.        , 0.        , 0.        ,
       0.03121836, 0.        , 0.01509932, 0.        , 0.        ,
       0.        , 0.01053029, 0.        , 0.02611884, 0.06004892,
       0.04787601, 0.02604114, 0.        , 0.08167271, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.02937431, 0.09738394,
       0.03466251, 0.06134277, 0.        , 0.00982116, 0.08091183,
       0.        , 0.02991196, 0.        , 0.02052689, 0.08449897,
       0.02680885, 0.06869517, 0.        , 0.        , 0.01864426,
       0.        , 0.01157709, 0.        , 0.07281383, 0.00317069,
       0.02992177, 0.03267543, 0.02618286, 0.01281544, 0.        ,
       0.05380776, 0.01742881, 0.02345625, 0.075359  , 0.08157011,
       0.02006556, 0.06471894, 0.04422614, 0.        , 0.        ,
       0.02189814, 0.        , 0.03532163, 0.02999916, 0.01203329,
       0.        , 0.0463447 , 0.04895584, 0.02601956, 0.        ,
       0.03148333, 0.        , 0.        , 0.05907847, 0.        ,
       0.01386146, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.19409305, 0.        ,
       0.        , 0.        , 0.        , 0.02428087, 0.        ,
       0.03889878, 0.        , 0.        , 0.        , 0.        ,
       0.05285586, 0.04656146, 0.00557954, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07402841, 0.        ,
       0.01598507, 0.        , 0.03400453, 0.        , 0.        ,
       0.03230578, 0.        , 0.        , 0.01447364, 0.04371918,
       0.        , 0.        , 0.        , 0.06291708, 0.        ,
       0.01746565])

In [54]:
print(len(X_item[0]))
X_item[0]

9066

array([1.        , 0.39451145, 0.30651588, ..., 0.        , 0.        ,
       0.05582876])

### Define a function to determine and return suitable recommendations to the user for items they have not interacted with yet.

In [81]:
def movie_recommender(user_item_m, X_user, user, k=20, top_n=10): 
    # Get location of the actual user in the User-Items matrix 
    user_ix = user_item_m.index.get_loc(user)
    print(f"Let's look at user with ID # {user} in row {user_ix}.")

    # Use it to index the User similarity matrix 
    user_similarities = X_user[user_ix]
    print(f"Here is their array of similarities:", user_similarities)

    # obtain the indices of the top k most similar users 
    most_similar_users = user_item_m.index[user_similarities.argpartition(-k)[-k:]] 
    print(f"From this list, the {k} most similar users are:",most_similar_users)
    
    # Obtain the mean ratings of those users for all movies 
    rec_movies = user_item_m.loc[most_similar_users].mean(0).sort_values(ascending=False) 
    print(f"\n\nThese {k} users gave the following average scores, listed highest to lowest, for all the movies in the database:", rec_movies[0:20])
    
    # Discard already seen movies 
    m_seen_movies = user_item_m.loc[user].gt(0)
    print('\n',np.count_nonzero(m_seen_movies), "movies have been seen in this database.")
    
    seen_movies = m_seen_movies.index[m_seen_movies].tolist()
    print("\nThe indices of the seen movies:", seen_movies)
    
    rec_movies = rec_movies.drop(seen_movies).head(top_n)
    print(f"\nThese are the top {top_n} highest average movies from the similar users that have not been seen:",rec_movies )
    
    # return recommendations - top similar users rated movies (and link to a list of movie names by id if you have that info)
    return rec_movies.index.to_frame().reset_index(drop=True)#.merge(movies)

In [83]:
movie_recommender(user_item_m, X_user, 1,)

Let's look at user with ID # 1 in row 0.
Here is their array of similarities: [1.         0.         0.         0.07448245 0.01681799 0.
 0.08388416 0.         0.01284289 0.         0.         0.
 0.         0.         0.05938727 0.         0.02107287 0.
 0.08563118 0.01656352 0.05733056 0.0436822  0.07024269 0.
 0.01491541 0.00262104 0.03501505 0.         0.         0.06130103
 0.02379292 0.03170691 0.00821267 0.08459736 0.13058496 0.01652849
 0.         0.03282542 0.0203909  0.         0.06833225 0.
 0.04105418 0.         0.         0.         0.         0.02081219
 0.07333877 0.         0.         0.         0.         0.03782836
 0.         0.03844173 0.06430548 0.         0.01381982 0.
 0.01399113 0.         0.         0.         0.         0.04528371
 0.         0.00203034 0.         0.03191959 0.         0.
 0.08815485 0.         0.04607949 0.05055473 0.05434844 0.02342739
 0.00638392 0.         0.00859143 0.         0.02156587 0.
 0.         0.         0.00868171 0.02296659 0.         0.0369091
 0.         0.         0.         0.02336634 0.06935038 0.01409893
 0.         0.01113426 0.01507229 0.         0.         0.11061886
 0.04105543 0.         0.06295552 0.         0.         0.
 0.         0.01793091 0.01085366 0.         0.         0.
 0.         0.         0.         0.06418191 0.10702625 0.0285293
 0.         0.         0.         0.         0.01861684 0.
 0.         0.01375495 0.         0.1128173  0.         0.
 0.04536836 0.01552579 0.         0.         0.0237856  0.
 0.         0.         0.03972436 0.         0.         0.
 0.         0.         0.         0.05662497 0.         0.03714867
 0.         0.01107776 0.         0.01615124 0.0547292  0.
 0.01478723 0.         0.         0.         0.01794253 0.
 0.         0.         0.03409791 0.         0.05243038 0.
 0.         0.         0.         0.         0.         0.
 0.02320688 0.         0.03256007 0.02416268 0.         0.
 0.         0.         0.         0.         0.05175364 0.02407593
 0.         0.03402944 0.         0.01577255 0.         0.
 0.01902068 0.         0.12264701 0.03295271 0.05239205 0.04105918
 0.01088565 0.         0.         0.06477871 0.         0.
 0.         0.         0.15274613 0.         0.         0.
 0.02566508 0.05341078 0.01317318 0.0893721  0.         0.
 0.02125244 0.         0.         0.02890549 0.         0.01880908
 0.         0.00838886 0.         0.0167404  0.         0.024441
 0.11257474 0.         0.         0.08976054 0.03849354 0.
 0.         0.01759041 0.         0.         0.         0.
 0.         0.03499459 0.03093657 0.         0.         0.
 0.03406709 0.03833662 0.         0.         0.         0.03293479
 0.00914493 0.01463585 0.         0.         0.02565598 0.
 0.         0.         0.         0.01833513 0.         0.
 0.07111912 0.         0.         0.0171179  0.         0.
 0.         0.         0.         0.         0.         0.08835959
 0.         0.         0.         0.08094778 0.04318461 0.00879305
 0.03622283 0.         0.05886316 0.         0.01821885 0.01813161
 0.         0.0812857  0.04983508 0.01492461 0.         0.04555866
 0.01887164 0.         0.02952889 0.         0.03439712 0.03196288
 0.         0.         0.04989034 0.01350079 0.         0.05781542
 0.         0.0100647  0.0556856  0.15752433 0.06084026 0.05034743
 0.01320346 0.         0.05814347 0.         0.         0.0287678
 0.         0.05669426 0.04967354 0.         0.         0.
 0.37185158 0.0261166  0.         0.0331263  0.         0.04684663
 0.         0.         0.         0.         0.07388513 0.
 0.01929173 0.02334196 0.         0.         0.16281929 0.03427715
 0.         0.02648466 0.         0.06791871 0.         0.
 0.         0.0194026  0.01850539 0.02797476 0.01458012 0.
 0.01432797 0.         0.         0.05614964 0.         0.04185099
 0.00807456 0.03088488 0.08244055 0.         0.         0.
 0.         0.         0.         0.03436955 0.         0.04596723
 0.06811539 0.         0.         0.         0.         0.
 0.         0.06232238 0.02266094 0.         0.         0.00906438
 0.         0.01245744 0.1054804  0.02847007 0.         0.04022741
 0.09150085 0.         0.         0.01662758 0.02517686 0.
 0.         0.04213583 0.         0.         0.06198436 0.
 0.10709466 0.03531453 0.06687343 0.         0.00656062 0.00865417
 0.         0.         0.         0.01075103 0.         0.
 0.         0.         0.         0.         0.02856747 0.02139239
 0.         0.         0.05569804 0.04632873 0.         0.
 0.         0.03188319 0.         0.03661603 0.01431953 0.
 0.         0.03429513 0.         0.0398459  0.         0.
 0.01990771 0.         0.03824504 0.03485761 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.07404574 0.         0.         0.         0.
 0.0418626  0.03261414 0.         0.03343253 0.07414096 0.
 0.07315209 0.         0.         0.04948608 0.02354118 0.0914953
 0.         0.07930017 0.01603946 0.0777233  0.         0.0094776
 0.         0.         0.06519841 0.         0.         0.01463942
 0.01885025 0.01363051 0.         0.         0.11402063 0.
 0.0219479  0.01908271 0.         0.         0.         0.
 0.         0.         0.         0.01844544 0.09022913 0.
 0.         0.0199359  0.         0.00579387 0.         0.
 0.05095534 0.         0.02320688 0.         0.07430613 0.0897871
 0.03398825 0.         0.         0.05074426 0.         0.03089229
 0.         0.08338221 0.01996347 0.02990439 0.05584664 0.01284349
 0.         0.         0.06978353 0.         0.05080105 0.
 0.06524185 0.02819785 0.         0.0280646  0.07019961 0.06007672
 0.         0.         0.04017221 0.         0.10436802 0.
 0.         0.         0.         0.0127034  0.06277648 0.06160218
 0.05767321 0.         0.         0.         0.03121836 0.
 0.01509932 0.         0.         0.         0.01053029 0.
 0.02611884 0.06004892 0.04787601 0.02604114 0.         0.08167271
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.02937431 0.09738394 0.03466251
 0.06134277 0.         0.00982116 0.08091183 0.         0.02991196
 0.         0.02052689 0.08449897 0.02680885 0.06869517 0.
 0.         0.01864426 0.         0.01157709 0.         0.07281383
 0.00317069 0.02992177 0.03267543 0.02618286 0.01281544 0.
 0.05380776 0.01742881 0.02345625 0.075359   0.08157011 0.02006556
 0.06471894 0.04422614 0.         0.         0.02189814 0.
 0.03532163 0.02999916 0.01203329 0.         0.0463447  0.04895584
 0.02601956 0.         0.03148333 0.         0.         0.05907847
 0.         0.01386146 0.         0.         0.         0.
 0.         0.         0.         0.19409305 0.         0.
 0.         0.         0.02428087 0.         0.03889878 0.
 0.         0.         0.         0.05285586 0.04656146 0.00557954
 0.         0.         0.         0.         0.         0.07402841
 0.         0.01598507 0.         0.03400453 0.         0.
 0.03230578 0.         0.         0.01447364 0.04371918 0.
 0.         0.         0.06291708 0.         0.01746565]
From this list, the 20 most similar users are: Index([497, 468, 391, 539, 575, 387, 207, 195, 130,  35, 310, 119, 403, 485,
       341, 102, 229, 634, 325,   1],
      dtype='int64', name='userId')


These 20 users gave the following average scores, listed highest to lowest, for all the movies in the database: movieId
1172    2.475
1293    2.175
318     2.000
1221    1.975
1339    1.950
608     1.900
1193    1.875
858     1.850
953     1.800
1225    1.800
1276    1.775
1207    1.700
527     1.700
1287    1.700
1035    1.675
1196    1.650
1208    1.625
1262    1.550
2968    1.525
920     1.525
dtype: float64

 20 movies have been seen in this database.

The indices of the seen movies: [31, 1029, 1061, 1129, 1172, 1263, 1287, 1293, 1339, 1343, 1371, 1405, 1953, 2105, 2150, 2193, 2294, 2455, 2968, 3671]

These are the top 10 highest average movies from the similar users that have not been seen: movieId
318     2.000
1221    1.975
608     1.900
1193    1.875
858     1.850
953     1.800
1225    1.800
1276    1.775
1207    1.700
527     1.700
dtype: float64

   movieId
0      318
1     1221
2      608
3     1193
4      858
5      953
6     1225
7     1276
8     1207
9      527

**Code Explanation Bit by Bit**

```python
user_item_m = ratings.pivot('userId', "movieId", 'rating').fillna(0)
```
* **`user_item_m = ratings.pivot('userId', "movieId", 'rating')`**: This is a key step in preparing the data for a memory-based recommender system.
    * **`ratings.pivot(...)`**: The `pivot` function in pandas is used to reshape a DataFrame based on column values.  Here, we're transforming the `ratings` DataFrame.
    * **`'userId'`**: This specifies that the 'userId' column from the `ratings` DataFrame will become the *index* (rows) of the new `user_item_m` DataFrame.  Each unique user ID will represent a row.
    * **`"movieId"`**: This specifies that the "movieId" column from the `ratings` DataFrame will become the *columns* of the new `user_item_m` DataFrame. Each unique movie ID will represent a column.
    * **`'rating'`**: This specifies that the 'rating' column from the `ratings` DataFrame will populate the *values* within the `user_item_m` DataFrame. The values will be the ratings given by each user (row) to each movie (column).
    * **Result**:  The `pivot` operation creates a user-item matrix where each row represents a user, each column represents a movie, and the cell at the intersection of a row and column contains the rating given by that user to that movie. If a user hasn't rated a particular movie, there will be a missing value (`NaN`) in that cell initially.

* **`.fillna(0)`**:  After the `pivot` operation, cells in `user_item_m` that represent user-movie pairs where no rating exists will be filled with `NaN` (Not a Number).  `.fillna(0)` replaces all these `NaN` values with `0`. In the context of recommender systems, a `0` rating often implies that the user has not interacted with the movie, and we treat it as a neutral or non-preference.  This is a common approach, but you might choose other strategies (like using the average rating) depending on the specifics of your data and problem.


```python
X_user = cosine_similarity(user_item_m)
X_item = cosine_similarity(user_item_m.T)
```
* **`X_user = cosine_similarity(user_item_m)`**:
    * **`cosine_similarity(user_item_m)`**: This applies the `cosine_similarity` function to the `user_item_m` matrix.
    * **`user_item_m`**:  When `cosine_similarity` is applied to the user-item matrix directly, it calculates the cosine similarity between *rows* of the matrix. In `user_item_m`, each row represents a user's ratings for all movies. Therefore, this line calculates the cosine similarity between each pair of *users*.
    * **`X_user = ...`**: The result, a matrix of user-user cosine similarities, is stored in the variable `X_user`. `X_user[i][j]` will represent the cosine similarity between user `i` and user `j`.

* **`X_item = cosine_similarity(user_item_m.T)`**:
    * **`user_item_m.T`**: `.T` is the transpose operation in NumPy. It transposes the `user_item_m` matrix, meaning rows become columns and columns become rows. After transposing, each *row* now represents a movie, and the columns are users.
    * **`cosine_similarity(user_item_m.T)`**: Applying `cosine_similarity` to the transposed matrix calculates the cosine similarity between the *rows* of the transposed matrix, which are the movies in the original matrix.  This computes the cosine similarity between each pair of *movies* based on user ratings.
    * **`X_item = ...`**: The result, a matrix of item-item cosine similarities, is stored in the variable `X_item`. `X_item[i][j]` will represent the cosine similarity between movie `i` and movie `j`.

```python
def movie_recommender(user_item_m, X_user, user, k=20, top_n=10):
```
* **`def movie_recommender(user_item_m, X_user, user, k=20, top_n=10):`**: This line defines a function named `movie_recommender`. This function is designed to generate movie recommendations for a specific user.
    * **`user_item_m`**: This is expected to be the user-item matrix (DataFrame) we created earlier.
    * **`X_user`**: This is the user-user cosine similarity matrix we calculated.
    * **`user`**: This is the ID of the user for whom we want to generate recommendations.
    * **`k=20`**: This is a parameter with a default value of 20. `k` will determine the number of most similar users to consider when making recommendations. It's often referred to as the "neighborhood size".
    * **`top_n=10`**: This is another parameter with a default value of 10. `top_n` will determine the number of top movie recommendations to return.

```python
    # Get location of the actual user in the User-Items matrix
    user_ix = user_item_m.index.get_loc(user)
    print(f"Let's look at user with ID # {user_ix}.")
```
* **`user_ix = user_item_m.index.get_loc(user)`**:
    * **`user_item_m.index`**:  This accesses the index of the `user_item_m` DataFrame, which we set to be user IDs using `pivot`.
    * **`.get_loc(user)`**:  This is a pandas `Index` method that gets the integer *location* (index position) for a given index label (`user`).  Since our index is user IDs, this line finds the numerical index (starting from 0) of the row corresponding to the user ID `user` within the `user_item_m` DataFrame.
    * **`user_ix = ...`**: The integer index location is stored in the variable `user_ix`. This is needed because we'll use this index to access the corresponding row in the `X_user` matrix.
    * **`print(f"Let's look at user with ID # {user_ix}.")`**: This line prints a message indicating which user (by their numerical index in the user-item matrix) we are generating recommendations for.

```python
    # Use it to index the User similarity matrix
    user_similarities = X_user[user_ix]
    print(f"Here is their array of similarities:", user_similarities)
```
* **`user_similarities = X_user[user_ix]`**:
    * **`X_user[user_ix]`**:  We use `user_ix` (the numerical index of the target user) to index into the `X_user` (user-user similarity) matrix. `X_user` is a 2D array where `X_user[i]` gives the array of cosine similarities of user `i` with all other users (including themselves). So, `X_user[user_ix]` retrieves a 1D array containing the cosine similarity scores of the target user (at index `user_ix`) with every other user in the system.
    * **`user_similarities = ...`**: This array of similarity scores is stored in the `user_similarities` variable.
    * **`print(f"Here is their array of similarities:", user_similarities)`**: This line prints the array of cosine similarity scores between the target user and all other users.

```python
    # obtain the indices of the top k most similar users
    most_similar_users = user_item_m.index[user_similarities.argpartition(-k)[-k:]]
    print(f"From this list, the {k} most similar users are:",most_similar_users)
```
* **`most_similar_users = user_item_m.index[user_similarities.argpartition(-k)[-k:]]`**: This is a crucial step to find the top `k` most similar users.
    * **`user_similarities.argpartition(-k)`**:
        * **`user_similarities`**: This is the 1D array of cosine similarities between the target user and all other users.
        * **`.argpartition(-k)`**:  `argpartition` is a NumPy function that performs a partial sort. `argpartition(-k)` finds the indices that would partition the array such that the elements at and after the k-th largest position are the largest k elements (in no particular order within that partition). It's more efficient than fully sorting the entire array when you only need to find the top k values. In this case, `argpartition(-k)` returns an array of indices.  The *last* `k` indices in this resulting array correspond to the indices of the `k` most similar users (but they are not yet sorted by similarity within these top k).
        * **`[-k:]`**:  This slices the result of `argpartition` to take only the *last* `k` indices. These indices point to the positions in the original `user_similarities` array that correspond to the top `k` most similar users.

    * **`user_item_m.index[...]`**:
        * **`user_item_m.index`**: This is the index of the `user_item_m` DataFrame, which are the user IDs.
        * **`[...]`**:  We use the indices obtained from `user_similarities.argpartition(-k)[-k:]` to index into `user_item_m.index`. This effectively retrieves the *user IDs* of the top `k` most similar users.

    * **`most_similar_users = ...`**: The list of user IDs of the top `k` similar users is stored in `most_similar_users`.
    * **`print(f"From this list, the {k} most similar users are:",most_similar_users)`**: This line prints the user IDs of the `k` most similar users identified.

```python
    # Obtain the mean ratings of those users for all movies
    rec_movies = user_item_m.loc[most_similar_users].mean(0).sort_values(ascending=False)
    print(f"\n\nThese {k} users gave the following average scores, listed highest to lowest, for all the movies in the database:", rec_movies[0:20])
```
* **`rec_movies = user_item_m.loc[most_similar_users].mean(0).sort_values(ascending=False)`**: This calculates the average ratings of the similar users for all movies and sorts them in descending order.
    * **`user_item_m.loc[most_similar_users]`**:
        * **`user_item_m`**: The user-item matrix.
        * **`.loc[most_similar_users]`**:  `.loc` is used for label-based indexing in pandas. `most_similar_users` is a list of user IDs. This selects the rows from `user_item_m` corresponding to the `most_similar_users`.  The result is a DataFrame containing the ratings of only the `k` most similar users for all movies.
    * **`.mean(0)`**:
        * **`.mean(0)`**:  Applies the `.mean()` function to the DataFrame from the previous step. The `0` argument specifies that the mean should be calculated along the *rows* (axis 0). In this context, for each movie (column), it calculates the average rating given by the `most_similar_users`.  This essentially averages the ratings of the similar users for each movie.
    * **`.sort_values(ascending=False)`**:
        * **`.sort_values(ascending=False)`**: Sorts the resulting `Series` (which contains the average ratings for each movie) in descending order. Movies with higher average ratings from similar users will appear at the top.
    * **`rec_movies = ...`**: The sorted Series of average movie ratings is stored in `rec_movies`.
    * **`print(f"\n\nThese {k} users gave the following average scores, listed highest to lowest, for all the movies in the database:", rec_movies[0:20])`**: This prints the top 20 average movie ratings from the similar users (before removing already seen movies).

```python
    # Discard already seen movies
    m_seen_movies = user_item_m.loc[user].gt(0)
    print('\n',np.count_nonzero(m_seen_movies), "movies have been seen in this database.")

    seen_movies = m_seen_movies.index[m_seen_movies].tolist()
    print("\nThe indices of the seen movies:", seen_movies)

    rec_movies = rec_movies.drop(seen_movies).head(top_n)
    print(f"\nThese are the top {top_n} highest average movies from the similar users that have not been seen:",rec_movies )
```
* **`m_seen_movies = user_item_m.loc[user].gt(0)`**:
    * **`user_item_m.loc[user]`**: Selects the row from `user_item_m` corresponding to the target `user`. This gives a `Series` of ratings given by this user to all movies.
    * **`.gt(0)`**:  `.gt(0)` (greater than 0) performs an element-wise comparison. For each rating in the Series, it checks if it's greater than 0. It returns a boolean `Series` where `True` indicates a rating > 0 (meaning the user has rated the movie, so we consider it as "seen"), and `False` means a rating of 0 (or less, though ratings are typically non-negative in this context).
    * **`m_seen_movies = ...`**: This boolean Series, indicating which movies the user has rated (and thus "seen"), is stored in `m_seen_movies`.
    * **`print('\n',np.count_nonzero(m_seen_movies), "movies have been seen in this database.")`**: This line counts and prints the number of movies the user has rated (i.e., "seen"). `np.count_nonzero(m_seen_movies)` counts the number of `True` values in the `m_seen_movies` boolean Series.

* **`seen_movies = m_seen_movies.index[m_seen_movies].tolist()`**:
    * **`m_seen_movies.index`**: This is the index of the `m_seen_movies` Series, which are the movie IDs.
    * **`m_seen_movies`**: Used as a boolean mask to index `m_seen_movies.index`. This effectively selects only the movie IDs where `m_seen_movies` is `True` (i.e., movies that the user has rated).
    * **`.tolist()`**: Converts the resulting pandas `Index` to a Python list.
    * **`seen_movies = ...`**: The list of movie IDs that the user has already seen is stored in `seen_movies`.
    * **`print("\nThe indices of the seen movies:", seen_movies)`**: This line prints the list of movie IDs that the user has already seen.

* **`rec_movies = rec_movies.drop(seen_movies).head(top_n)`**:
    * **`rec_movies.drop(seen_movies)`**:  `rec_movies` is the Series of average movie ratings from similar users, sorted in descending order. `.drop(seen_movies)` removes the movie IDs present in the `seen_movies` list from `rec_movies`. This ensures that we don't recommend movies that the user has already seen.
    * **`.head(top_n)`**: After dropping the seen movies, `.head(top_n)` selects the top `top_n` movies from the remaining recommendations. These are the top-ranked movies from similar users that the target user has not yet seen.
    * **`rec_movies = ...`**: The final list of top `top_n` recommended movies (as a pandas Series) is stored back into `rec_movies`.
    * **`print(f"\nThese are the top {top_n} highest average movies from the similar users that have not been seen:",rec_movies )`**: This line prints the top `top_n` recommended movies.

```python
    # return recommendations - top similar users rated movies (and link to a list of movie names by id if you have that info)
    return rec_movies.index.to_frame().reset_index(drop=True)#.merge(movies)
```
* **`return rec_movies.index.to_frame().reset_index(drop=True)`**: This line prepares and returns the final recommendations.
    * **`rec_movies.index`**:  `rec_movies` is a pandas Series, and `.index` accesses its index, which in this case is movie IDs.
    * **`.to_frame()`**: Converts the `Index` (movie IDs) into a pandas DataFrame.
    * **`.reset_index(drop=True)`**: Resets the index of the DataFrame to a default integer index (0, 1, 2, ...), and `drop=True` prevents the old index (movie IDs) from becoming a new column in the DataFrame. It just discards the old index and creates a new default one.
    * **`return ...`**: The function returns this DataFrame, which essentially is a list of movie IDs that are recommended.
    * **`#.merge(movies)`**:  This is a commented-out part of the code. It suggests that if you had another DataFrame called `movies` that contained movie IDs and movie names, you could use `.merge(movies)` to join the recommendations with movie names to make the output more user-friendly.

```python
recommendations = movie_recommender(user_item_m, X_user, 10,)
```
* **`recommendations = movie_recommender(user_item_m, X_user, 10,)`**: This line *calls* the `movie_recommender` function.
    * **`user_item_m, X_user`**: These are passed as the first two arguments (user-item matrix and user similarity matrix).
    * **`10`**: This is passed as the `user` argument. So, we are requesting recommendations for user with ID 10.
    * **`recommendations = ...`**: The returned value from the `movie_recommender` function (which is a DataFrame of recommended movie IDs) is assigned to the variable `recommendations`.

**Step-by-Step Guide**

**Step 1: Get the Dataset**

1. **Download `ratings_small.csv`** 

**Step 2: Create a Python File and Import Libraries**

1. **Create a Python file:** Open a text editor or an IDE (like VS Code, PyCharm, Jupyter Notebook, etc.). Create a new file and save it as, for example, `recommender.py`.
2. **Import Libraries:** In your `recommender.py` file, start by importing the necessary libraries:
   ```python
   import pandas as pd
   import numpy as np
   from sklearn.metrics.pairwise import cosine_similarity
   ```

**Step 3: Load and Prepare the Data**

1. **Load the CSV file:** Add code to read the `ratings_small.csv` file into a pandas DataFrame:
   ```python
   ratings = pd.read_csv("data/ratings_small.csv")
   ```
2. **Create the User-Item Matrix:**  Reshape the `ratings` DataFrame into a user-item matrix using the `pivot` function, and fill missing values with 0:
   ```python
   user_item_m = ratings.pivot('userId', "movieId", 'rating').fillna(0)
   ```

**Step 4: Calculate Similarity Matrices**

1. **Calculate User-User Cosine Similarity:** Compute the cosine similarity between users based on their ratings:
   ```python
   X_user = cosine_similarity(user_item_m)
   ```
2. **Calculate Item-Item Cosine Similarity (Optional for this function but calculated in the code):** Compute the cosine similarity between movies (items):
   ```python
   X_item = cosine_similarity(user_item_m.T)
   ```

**Step 5: Define the Recommendation Function**

1. **Start Function Definition:** Define the `movie_recommender` function, including parameters for user-item matrix, user similarity matrix, target user ID, number of similar users (`k`), and number of top recommendations (`top_n`):
   ```python
   def movie_recommender(user_item_m, X_user, user, k=20, top_n=10):
       # Function code will go here
   ```
2. **Get User Index:** Inside the function, find the numerical index of the target user in the user-item matrix:
   ```python
       user_ix = user_item_m.index.get_loc(user)
       print(f"Let's look at user with ID # {user_ix}.")
   ```
3. **Get User Similarities:** Get the array of similarity scores for the target user from the user similarity matrix:
   ```python
       user_similarities = X_user[user_ix]
       print(f"Here is their array of similarities:", user_similarities)
   ```
4. **Find Top K Similar Users:** Identify the IDs of the top `k` most similar users:
   ```python
       most_similar_users = user_item_m.index[user_similarities.argpartition(-k)[-k:]]
       print(f"From this list, the {k} most similar users are:",most_similar_users)
   ```
5. **Calculate Average Ratings from Similar Users:** Compute the average rating for each movie given by the similar users, and sort in descending order:
   ```python
       rec_movies = user_item_m.loc[most_similar_users].mean(0).sort_values(ascending=False)
       print(f"\n\nThese {k} users gave the following average scores, listed highest to lowest, for all the movies in the database:", rec_movies[0:20])
   ```
6. **Exclude Already Seen Movies:** Filter out movies that the target user has already rated:
   ```python
       m_seen_movies = user_item_m.loc[user].gt(0)
       print('\n',np.count_nonzero(m_seen_movies), "movies have been seen in this database.")
       seen_movies = m_seen_movies.index[m_seen_movies].tolist()
       print("\nThe indices of the seen movies:", seen_movies)
       rec_movies = rec_movies.drop(seen_movies).head(top_n)
       print(f"\nThese are the top {top_n} highest average movies from the similar users that have not been seen:",rec_movies )
   ```
7. **Return Recommendations:** Return the top `top_n` movie IDs as a DataFrame:
   ```python
       return rec_movies.index.to_frame().reset_index(drop=True)
   ```

**Step 6: Use the Recommender Function and Print Results**

1. **Call the Function:** Outside of the function definition, call `movie_recommender` to get recommendations for a specific user (e.g., user ID 10):
   ```python
   recommendations = movie_recommender(user_item_m, X_user, 10)
   ```
2. **Print Recommendations:** Print the `recommendations` DataFrame to see the recommended movie IDs:
   ```python
   print("\nRecommended Movies:")
   print(recommendations)
   ```

In [57]:
recommendations = movie_recommender(user_item_m, X_user, 11,)

Let's look at user with ID # 10.
Here is their array of similarities: [0.         0.04961008 0.09200445 0.01898684 0.02069262 0.
 0.00578207 0.06181342 0.0180591  0.03770778 1.         0.
 0.06892561 0.         0.10249781 0.03913813 0.06225262 0.02284546
 0.06188853 0.01441817 0.03412304 0.04688122 0.06245884 0.05704552
 0.04194676 0.08661125 0.11283387 0.         0.05768662 0.03394274
 0.06217341 0.01486161 0.01154829 0.0785966  0.         0.06456005
 0.         0.06966385 0.05734555 0.08589767 0.         0.09255992
 0.00233247 0.         0.         0.08495507 0.06404634 0.07117577
 0.         0.03423834 0.         0.         0.02746313 0.10786267
 0.         0.09729907 0.01900204 0.         0.05829842 0.
 0.02185967 0.05226414 0.03121192 0.05186767 0.         0.
 0.04239098 0.02212601 0.01789501 0.01745485 0.         0.13380805
 0.10804056 0.03577556 0.03715837 0.         0.02197142 0.07782678
 0.02693034 0.0635849  0.0226277  0.07523863 0.05802924 0.08037459
 0.02744735 0.03557239 0.05595259 0.03455174 0.06723722 0.02594996
 0.03798223 0.0708824  0.02890042 0.07823024 0.04381217 0.06872768
 0.10805909 0.06106036 0.04317292 0.         0.02641257 0.0503782
 0.02259012 0.06377499 0.07662268 0.01516872 0.07973601 0.02923027
 0.04391425 0.02101137 0.04825675 0.05052206 0.         0.
 0.01743503 0.07586091 0.         0.04495198 0.06702742 0.04703328
 0.0530291  0.01025762 0.05526444 0.02959902 0.06302151 0.
 0.         0.008059   0.03123695 0.02717421 0.02265871 0.04846084
 0.07655395 0.06401264 0.06564483 0.         0.05574375 0.21168124
 0.01095983 0.03603369 0.         0.01721938 0.06081663 0.04141889
 0.02063018 0.03802605 0.1078844  0.         0.09157048 0.08971745
 0.05027808 0.07380552 0.0497873  0.         0.         0.05379239
 0.11813586 0.         0.08359633 0.01447078 0.01681999 0.
 0.05181267 0.02555276 0.04290749 0.03034295 0.         0.04253394
 0.03123846 0.         0.05721552 0.10373533 0.03414268 0.
 0.02266144 0.08103305 0.01844099 0.0686608  0.01402702 0.
 0.0426231  0.01812474 0.09121593 0.03776452 0.04263507 0.03009289
 0.07279775 0.02658371 0.02818538 0.0400448  0.05656167 0.
 0.01671627 0.02337367 0.03437943 0.01544554 0.         0.01528295
 0.14975269 0.05415772 0.04667007 0.02335614 0.03936032 0.04424926
 0.08362901 0.         0.05820726 0.05851614 0.         0.
 0.02165345 0.08232929 0.05362677 0.04833502 0.         0.01457978
 0.         0.01602792 0.04619106 0.05604167 0.         0.01959147
 0.         0.04423515 0.0264037  0.         0.         0.03436785
 0.         0.08075978 0.10808144 0.06256459 0.         0.02093889
 0.04564884 0.02378351 0.04714617 0.04287874 0.0228319  0.05100209
 0.09302472 0.05050277 0.02963846 0.0063928  0.05489896 0.02475622
 0.03321318 0.01796908 0.         0.0621773  0.07363244 0.
 0.06447457 0.05488075 0.01912658 0.         0.05511656 0.02424406
 0.02093895 0.         0.03549207 0.03491318 0.04122024 0.
 0.0354626  0.05721429 0.09893735 0.07169365 0.         0.12764457
 0.06333135 0.02935984 0.12902884 0.0657724  0.14848748 0.09525627
 0.01688542 0.05689146 0.05385253 0.03794172 0.05060355 0.02976614
 0.06680595 0.         0.03772544 0.         0.07205213 0.02832873
 0.         0.05914841 0.01313922 0.03905786 0.         0.01050348
 0.04391151 0.04159767 0.0338329  0.03959652 0.02021337 0.01498159
 0.         0.         0.0629448  0.10893319 0.03656362 0.04698644
 0.101283   0.00539144 0.06287936 0.03654438 0.04122348 0.05834141
 0.03218127 0.02752941 0.01635175 0.06081764 0.0114091  0.02696799
 0.         0.07042016 0.05587897 0.         0.         0.06339046
 0.         0.         0.02981901 0.00905736 0.         0.02195788
 0.         0.00964127 0.03422266 0.08958595 0.01731566 0.00925735
 0.         0.02188161 0.02818099 0.02732958 0.         0.04351298
 0.04973694 0.08922453 0.04144815 0.01041865 0.03312671 0.02580801
 0.         0.02425161 0.         0.05900529 0.07424179 0.
 0.06790403 0.         0.         0.06995738 0.         0.04086735
 0.03027755 0.07031351 0.02268853 0.02880429 0.01745047 0.
 0.         0.         0.05109299 0.03366194 0.08073814 0.
 0.04789041 0.         0.04131843 0.         0.         0.07234679
 0.08981715 0.0935458  0.01911888 0.0148126  0.0348211  0.05855158
 0.05410419 0.03736982 0.01358258 0.06982984 0.         0.05472644
 0.04428666 0.01085267 0.0111378  0.08529721 0.         0.03286779
 0.01737091 0.         0.11378012 0.06950883 0.         0.05085111
 0.02952779 0.         0.01263904 0.01868545 0.06073295 0.06152161
 0.05731484 0.00861813 0.02301233 0.0533316  0.         0.
 0.07456668 0.01713575 0.03584278 0.01032042 0.04984093 0.04562289
 0.         0.02902529 0.09054026 0.         0.05128267 0.03391456
 0.01363322 0.11859596 0.         0.05203267 0.03355914 0.05493295
 0.07179178 0.07050975 0.02561066 0.02918204 0.0534071  0.21772362
 0.         0.05652076 0.03092262 0.02904605 0.02849014 0.
 0.05473821 0.         0.02015758 0.03633722 0.04572134 0.10897524
 0.         0.03955123 0.01703336 0.15601994 0.03711348 0.03647433
 0.11082919 0.02397937 0.         0.04731268 0.06358994 0.02624293
 0.03657358 0.04115875 0.03432575 0.06857664 0.01471225 0.07560233
 0.         0.02570598 0.02470197 0.04981115 0.05175082 0.
 0.11769163 0.0390505  0.00550075 0.12067806 0.10586577 0.09324653
 0.0696897  0.00383332 0.11101345 0.         0.02915104 0.03734065
 0.03703459 0.03737489 0.03977944 0.         0.01985232 0.
 0.01016279 0.09460925 0.         0.         0.02114603 0.
 0.03831671 0.00350412 0.13555546 0.08147082 0.03044754 0.03073288
 0.02978092 0.03808775 0.02447436 0.07041276 0.05517592 0.04690709
 0.0796546  0.03485913 0.05293095 0.07436158 0.05317148 0.02262467
 0.         0.03335853 0.07728394 0.04993463 0.07656583 0.13958835
 0.05932129 0.04383027 0.03615186 0.02895957 0.07565076 0.05948983
 0.03632737 0.         0.00635759 0.01973159 0.01754872 0.05362205
 0.02348687 0.04652421 0.04788061 0.03120939 0.09219391 0.050777
 0.08512086 0.02763348 0.         0.10188501 0.03334776 0.05297996
 0.06668016 0.07046779 0.05561407 0.04138405 0.02621678 0.05482931
 0.12216819 0.0205026  0.05437272 0.05232806 0.         0.
 0.00535604 0.03530599 0.03842529 0.04641279 0.13310851 0.04225411
 0.         0.04652421 0.0609417  0.0301436  0.00901833 0.05448361
 0.         0.07952384 0.03454031 0.07865497 0.03066451 0.
 0.02901627 0.05342642 0.         0.08098242 0.03643807 0.
 0.12637772 0.03919802 0.0453387  0.09214921 0.04024837 0.07159387
 0.02434924 0.05243345 0.         0.02713199 0.02884675 0.03626226
 0.04198406 0.07452205 0.0246381  0.06933899 0.05062903 0.08729801
 0.03439185 0.06580747 0.06642437 0.         0.01158588 0.07465295
 0.06432019 0.05322467 0.03780725 0.02351006 0.02394948 0.02438977
 0.03449145 0.05021842 0.09695813 0.02230567 0.02172262 0.0409759
 0.08130565 0.0625004  0.02213523 0.02196273 0.05654187 0.08984415
 0.10610914 0.02512221 0.08160593 0.03101956 0.02684656 0.02735883
 0.         0.03697258 0.03253804 0.         0.10444659 0.04362727
 0.04606583 0.         0.03034905 0.         0.0124313  0.
 0.07030829 0.03103931 0.         0.0130951  0.06765506 0.0812357
 0.05094855 0.         0.         0.         0.01984085 0.03262412
 0.05653091 0.01123875 0.06058403 0.04553871 0.03257626 0.05848556
 0.04122074 0.02186626 0.         0.12734018 0.01912585 0.03942083
 0.03153912 0.0550042  0.0258041  0.0437829  0.06048892]
From this list, the 20 most similar users are: Index([399, 475, 157, 428, 563, 553, 478, 583, 270, 664, 273,  72, 138, 501,
       454, 275, 438, 522,  11, 199],
      dtype='int64', name='userId')


These 20 users gave the following average scores, listed highest to lowest, for all the movies in the database: movieId
296      4.275
79132    4.150
2959     3.925
58559    3.750
48516    3.325
2571     3.225
4993     2.975
50       2.925
91529    2.875
68157    2.825
5952     2.825
858      2.700
260      2.675
99114    2.650
33794    2.600
7153     2.550
318      2.525
59315    2.475
1196     2.450
80463    2.425
dtype: float64

 38 movies have been seen in this database.

The indices of the seen movies: [50, 70, 126, 169, 296, 778, 785, 923, 1027, 1201, 1408, 1918, 2042, 2596, 2762, 3424, 5669, 6598, 26614, 48516, 51084, 58295, 71211, 77455, 79132, 80489, 80906, 81158, 81562, 88129, 91500, 91529, 91548, 96079, 96861, 97938, 104841, 106487]

These are the top 10 highest average movies from the similar users that have not been seen: movieId
2959     3.925
58559    3.750
2571     3.225
4993     2.975
68157    2.825
5952     2.825
858      2.700
260      2.675
99114    2.650
33794    2.600
dtype: float64

In [38]:
recommendations

   movieId
0      260
1      589
2     2028
3      593
4     1270
5     4993
6     5952
7      590
8      356
9      110