# <center> Recommender Systems</center>
##  <center> Popularity Based Recommenders <br> MovieLens Movies Database </center>
<center>by: Nicole Woodland, P. Eng. for RoboGarden Inc. </center>

---

Why do we spend an entire module on Recommender Engines? 
<br> Because there is a signifigant and increasing market for recommender engine expertise! 
Here is the data: 
- these systems were valued at USD 1.77 B (2020) and USD 3.9B (2024)
- Overall estimated ML market of about USD 35 B in 2024
- That's approximately 11% market share for Recommender Engines
- Expected to experience significant growth, to possibly USD 33.2 B  by 2030!
  <br>
<img src = "https://www.grandviewresearch.com/static/img/research/us-recommendation-engine-market.png"> 
<br>**Some prominent players in the global recommendation engine include:**

- Adobe
- Amazon Web Services, Inc.
- Google LLC
- Hewlett Packard Enterprise Development LP
- International Business Machines Corporation
- Intel Corporation
- Microsoft Corporation
- Oracle
- Salesforce.com, Inc.
- SAP SE

#### Some Helpful References:
1. Comprehensive Guide to Recommender Engines: https://www.analyticsvidhya.com/blog/2018/06/comprehensive-guide-recommendation-engine-python/
2. GitHub Project Full Movie Recommender with Enhancements: https://github.com/jalajthanaki/Movie_recommendation_engine/blob/master/Movie_recommendation_engine.ipynb

---
#### Ask the Right Question:

In this example, we have a database of Movies and information about them. <br> Can we use this data to make movie recommendations meaningful to the user?

### <font color='blue'> Download the Dataset </font>
Download the Dataset from the following link: <br>
https://www.kaggle.com/rounakbanik/the-movies-dataset?select=movies_metadata.csv

In [3]:
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

<font color = "blue"> Read the dataset into the Pandas Data Frame!

In [5]:
import pandas as pd
df = pd.read_csv("movies_metadata.csv")

# There may be a few errors in the file, so the simplest thing to do it ignore those lines with the error_bad_lines option

In [6]:
df.head(4)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0

In [7]:
df.describe()

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

In [43]:
len_metadata = len(df['id'].unique())
print(len_metadata)

45436

In [9]:
df.head(3).transpose()

,0,1,2
adult,False,False,False
belongs_to_collection,"{'id': 10194, 'name': 'Toy Story Collection', ...",NaN,"{'id': 119050, 'name': 'Grumpy Old Men Collect..."
budget,30000000,65000000,0
genres,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'id': 10749, 'name': 'Romance'}, {'id': 35, ..."
homepage,http://toystory.disney.com/toy-story,NaN,NaN
id,862,8844,15602
imdb_id,tt0114709,tt0113497,tt0113228
original_language,en,en,en
original_title,Toy Story,Jumanji,Grumpier Old Men
overview,"Led by Woody, Andy's toys live happily in his ...",When siblings Judy and Peter discover an encha...,A family wedding reignites the ancient feud be...
popularity,21.946943,17.015539,11.7129
poster_path,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
production_companies,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'..."
production_countries,"[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o..."
release_date,1995-10-30,1995-12-15,1995-12-22
revenue,373554033.0,262797249.0,0.0
runtime,81.0,104.0,101.0
spoken_languages,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'en', 'name': 'English'}]"
status,Released,Released,Released
tagline,NaN,Roll the dice and unleash the excitement!,Still Yelling. Still Fighting. Still Ready for...
title,Toy Story,Jumanji,Grumpier Old Men
video,False,False,False
vote_average,7.7,6.9,6.5
vote_count,5415.0,2413.0,92.0

### <font color = "blue"> Popularity Based Recommender

Find the 5 highest ranked movies in the dataset!

In [11]:
top5Recommendations = df.sort_values(by = 'vote_average',
                                     ascending = False).head(5)
top5Recommendations

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
21642,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,320849,tt0886500,en,Ice Age Columbus: Who Were the First Americans?,Firmly rooted in the latest scientific discove...,...,2005-01-01,0.0,0.0,[],Released,NaN,Ice Age Columbus: Who Were the First Americans?,False,10.0,1.0
15710,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,96451,tt1587373,en,If God Is Willing and da Creek Don't Rise,"In 2006, director Spike Lee created an astonis...",...,2010-08-23,0.0,255.0,[],Released,NaN,If God Is Willing and da Creek Don't Rise,False,10.0,1.0
22396,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,72123,tt1341746,en,Meat the Truth,Meat the Truth is a high-profile documentary w...,...,2008-10-03,0.0,74.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Meat the Truth,False,10.0,1.0
22395,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",http://www.marvinhamlischmovie.com/,230864,tt3011874,en,Marvin Hamlisch: What He Did For Love,When Marvin Hamlisch passed away in August 201...,...,2013-10-12,0.0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Marvin Hamlisch: What He Did For Love,False,10.0,1.0
35343,False,NaN,300000,"[{'id': 35, 'name': 'Comedy'}, {'id': 99, 'nam...",NaN,140595,tt0308213,en,Elaine Stritch: At Liberty,Judy at the Palace. Sinatra at Carnegie Hall. ...,...,2002-01-01,0.0,140.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Legendary performances come along so rarely.,Elaine Stritch: At Liberty,False,10.0,1.0

Not an appropriate recommender because not enough people have reviewed each of the titles!

Find the 5 most voted on movies in the dataset!

### <font color = "blue"> Popularity Based Recommender

**Find the 5 highest weighted ranked movies in the dataset!**

In [14]:
top5Votes = df.sort_values(by = 'vote_count',ascending = False).head(5)
top5Votes

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
15480,False,NaN,160000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://inceptionmovie.warnerbros.com/,27205,tt1375666,en,Inception,"Cobb, a skilled thief who commits corporate es...",...,2010-07-14,8.255328e+08,148.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Your mind is the scene of the crime.,Inception,False,8.1,14075.0
12481,False,"{'id': 263, 'name': 'The Dark Knight Collectio...",185000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",http://thedarkknight.warnerbros.com/dvdsite/,155,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,...,2008-07-16,1.004558e+09,152.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Why So Serious?,The Dark Knight,False,8.3,12269.0
14551,False,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.avatarmovie.com/,19995,tt0499549,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",...,2009-12-10,2.787965e+09,162.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Enter the World of Pandora.,Avatar,False,7.2,12114.0
17818,False,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,24428,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,...,2012-04-25,1.519558e+09,143.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some assembly required.,The Avengers,False,7.4,12000.0
26564,False,"{'id': 448150, 'name': 'Deadpool Collection', ...",58000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.foxmovies.com/movies/deadpool,293660,tt1431045,en,Deadpool,Deadpool tells the origin story of former Spec...,...,2016-02-09,7.831130e+08,108.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Witness the beginning of a happy ending,Deadpool,False,7.4,11444.0

**Find the 5 highest revenue movies in the dataset!**

In [16]:
top5Budget = df.sort_values(by = 'revenue',ascending = False).head(5)
top5Budget["original_title"]

14551                          Avatar
26555    Star Wars: The Force Awakens
1639                          Titanic
17818                    The Avengers
25084                  Jurassic World
Name: original_title, dtype: object

**Find the 5 highest revenue movies by genre in the dataset!**

In [18]:
genre = "Comedy"

df_genre = df[df['genres'].str.contains(genre)]
df_genre = df_genre.sort_values(by = 'revenue',ascending = False).head(5)
df_genre["original_title"].head(5)

30700            Minions
15348        Toy Story 3
38176       Finding Dory
36253           Zootopia
44009    Despicable Me 3
Name: original_title, dtype: object

![Alt text](RetailRecommenderEngines.jpg "Retail Reccomender Engines")

## Use a Weighted Rating
<font color = "blue"> Create a function named popularity Recommender and use it to recommend books based on popularity. <br>
Use a weighted rank similar to that used in the IMDB rating example in lesson 2.
    
![alt text](IMDB.jpg "IMDB Calculation")

In [21]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [22]:
def popularityRecommender(df):
    
    #Define the minimum vote count
    minimum_vote_count = 0.75 * df['vote_count'].max()
    
    #Define C – the mean rating
    mean_rating = df['vote_average'].mean()

    df['weighted_rating'] = (((df['vote_count']/(df['vote_count']+minimum_vote_count)) * df['vote_average']) +
                             ((minimum_vote_count/(df['vote_count']+minimum_vote_count))*mean_rating))

    recommendations = df.sort_values(by = 'weighted_rating',ascending = False).head(5)
    
    return(recommendations)

In [23]:
top5 = popularityRecommender(df)
top5[["title",'vote_count','vote_average','weighted_rating',]].head(5)

                          title  vote_count  vote_average  weighted_rating
12481           The Dark Knight     12269.0           8.3         7.059721
15480                 Inception     14075.0           8.1         7.036375
2843                 Fight Club      9678.0           8.3         6.900903
22879              Interstellar     11187.0           8.1         6.895101
314    The Shawshank Redemption      8358.0           8.5         6.891640

In [24]:
top5Names = top5["title"].head(5).values
print(top5Names)

['The Dark Knight' 'Inception' 'Fight Club' 'Interstellar'
 'The Shawshank Redemption']